### ISSUE TITLE
Add capability to share the images using WebShare api

### ISSUE THREAD

**Issue by prabirshrestha** [igordanchenko/yet-another-react-lightbox#105]
### Is your feature request related to a problem? Please describe.

Currently there is no easy way to share images. This would be very useful on the phone.

### Describe the solution you'd like

WebShare api can be found at https://developer.mozilla.org/en-US/docs/Web/API/Web_Share_API. 
You can try the demo. https://w3c.github.io/web-share/demos/share-files.html

If possible I would also like to have an option where user can select additional options. For example I may want the user to download RAW images or JPEG which is compatible with others.

### Describe alternatives you've considered

Add download button.

**Comment by igordanchenko** [comment]
I appreciate you proposing this feature. I can see how it could be beneficial on mobile devices, but I'm concerned that releasing it as an official plugin would be premature, as the Web Share API is currently [fully supported](https://caniuse.com/web-share) only in 67% of browsers.

In the meantime, I would be happy to share a draft of the plugin with you, which you are more than welcome to use in your project as a custom plugin.

https://codesandbox.io/s/yet-another-react-lightbox-105-rjvyek?file=/src/Share.tsx

Also, you mentioned the download button as an alternative solution. I have had this feature sitting in my backlog for some time now, so I will go ahead and release it later today.

I hope these address your use case.

**Comment by prabirshrestha** [comment]
Download and share works. Thanks for the quick response!

**Comment by igordanchenko** [comment]
Re-opening this feature request considering the subsequent requests for the Share plugin.
