### ISSUE TITLE
Import error on useState?

### ISSUE THREAD

**Issue by Tcox-int** [igordanchenko/yet-another-react-lightbox#117]
### Describe the bug

When I import Lightbox into my project, I am unable to compile (using NEXtjs) as I am getting the following error:

./node_modules/yet-another-react-lightbox/dist/core/components/ImageSlide.js
Attempted import error: 'useState' is not exported from 'react' (imported as 'React').

### Expected behavior

Lightbox works and is able to compile in a NEXTjs project without an error on a base React hook.

### How to reproduce

I just import Lightbox

import Lightbox from "yet-another-react-lightbox";

### Screenshots / Logs

![image](https://user-images.githubusercontent.com/131289343/236304081-22f9a8ea-031f-467d-b20c-7f784997298a.png)

**Comment by igordanchenko** [comment]
What versions of React and Next.js are you using?

**Comment by Tcox-int** [comment]
React 18.2, NEXTjs 13.0.5

**Comment by igordanchenko** [comment]
And what is your node version?

**Comment by Tcox-int** [comment]
v16.15.1

**Comment by igordanchenko** [comment]
Are you by any chance using the `app` directory and trying to render the lightbox in a server component?

**Comment by Tcox-int** [comment]
I am, yes, but I am pretty sure I tossed a 'use client' at the top of the page.  Let me double check, see if that could be the issue?

**Comment by igordanchenko** [comment]
I'm pretty sure that's the culprit. I'm getting the exact error you described if I remove the `"use client"`.

**Comment by Tcox-int** [comment]
Ok, I'll give it a shot.  If that is all it is, I'm sorry to have bothered you =).  I'll let you know in just a moment.

**Comment by Tcox-int** [comment]
UPDATE: Yeah, I was a moron.  It was certainly a EBCAK.  Sorry about that.
