### ISSUE TITLE
Active Slide Reset while Scrolling

### ISSUE THREAD

**Issue by inthisar-hamza** [igordanchenko/yet-another-react-lightbox#127]
### Describe the bug

https://github.com/igordanchenko/yet-another-react-lightbox/assets/13174985/7382bb5b-7484-430c-9cbc-349f97e5bb94

Everything was fine in the Older version (V2.6.0) but after the latest version, I got these bug and I dont have any clue why it happens (the slider get reset active position) while scrolling down or up.

### Expected behavior

The inline Slider must stay at the last active slide position when scrolling

### How to reproduce

```jsx
{imageArray && imageArray.length > 0 && (
  <Lightbox
    index={0}
    key={imageArray.length}
    slides={imageArray.map((item) => ({
      src: String(item?.ImageUrl),
      imageFit: "cover",
      width: 1200,
      height: 800,
      type: "image",
    }))}
    inline={{
      style: {
        width: "100%",
        maxWidth: "900px",
        height: "100%",
        padding: 0,
        margin: 0,
      },
    }}
    styles={{
      container: {
        backgroundColor: "rgba(0, 0, 0, 0.0)",
        width: "100%",
        maxWidth: "900px",
        height: "100%",
        padding: 0,
        margin: 0,
      },
      icon: { color: "white" },
    }}
    carousel={{
      spacing: 0,
      padding: 0,
      imageFit: "cover",
    }}
    plugins={[Inline, Fullscreen, Slideshow]}
    render={{ slide: NextJsImage }}
    animation={{ swipe: 1000 }}
  />
)}
```

**Comment by igordanchenko** [comment]
Did you have a chance to read through the [v3 Breaking Changes](https://github.com/igordanchenko/yet-another-react-lightbox/issues/90)?

It sounds like your page is re-rendering when you scroll it. Wrapping `imageArray.map(...)` in a `useMemo` / `useState` should resolve this issue. Also, make sure to remove the `index={0}` prop.

p.s. You probably also no longer need to assign the key prop in v3 `key={imageArray.length}`
