### ISSUE TITLE
Potentially inflexible types

### ISSUE THREAD

**Issue by ekeric13** [igordanchenko/yet-another-react-lightbox#130]
### Describe the bug

I am using the renderProp to create custom slides that work better with nextjs following this example:

https://yet-another-react-lightbox.com/examples/nextjs

This is the typescript version:
https://codesandbox.io/p/sandbox/yet-another-react-lightbox-nextjs-ts-dt0l1m?file=%2Fsrc%2FNextJsImage.tsx%3A1%2C1

I am having issues modifying one of the types. Specifically I know for sure that there will be an alt, width, and height property to SlideImage.

Currently typescript is complaining about them missing:
<img width="600" alt="Screenshot 2023-05-23 at 2 52 42 PM" src="https://github.com/igordanchenko/yet-another-react-lightbox/assets/6489651/80e5fcd2-62cc-451f-8d03-77e067edbb3d">

But when I do this:
```ts
interface SpecificSlideImage extends SlideImage {
  alt: string;
  width: number;
  height: number;
}

interface NextJsImageProps extends RenderSlideProps {
  slide: SpecificSlideImage;
}

function NextJsImage({ slide, rect, offset }: NextJsImageProps) {
```

I get a type error with the renderProp...
<img width="600" alt="Screenshot 2023-05-23 at 2 53 29 PM" src="https://github.com/igordanchenko/yet-another-react-lightbox/assets/6489651/7d5c2a97-bab6-4bba-a1ea-3e9d67d1a0fc">

So kind of going in circles.

The caveat is this could be that I am not strong enough with typescript. Maybe this is a complete non-issue.

My current fix is to do this:
```ts
function NextJsImage({ slide, rect, offset }: RenderSlideProps) {
  if (
    slide.alt === undefined ||
    slide.width === undefined ||
    slide.height === undefined
  ) {
    throw new Error('Invalid slide properties');
  }
```

But it would be nice to define the interface explicitly

### Expected behavior

Be able to successfully extend the interfaces

### How to reproduce

Copy and paste the code above

**Comment by igordanchenko** [comment]
I can think of 3 different approaches here.

1) Add custom props to the `SlideImage` interface (assuming that _all_ your image slides will have these required attributes)

```tsx
// yet-another-react-lightbox.d.ts

declare module "yet-another-react-lightbox" {
  interface SlideImage {
    requiredAlt: string;
    requiredWidth: number;
    requiredHeight: number;
  }
}

export {};
```

```tsx
// NextJsImage.tsx

import Image from "next/image";
import type { RenderSlideProps } from "yet-another-react-lightbox";

export default function NextJsImage({
  slide: { src, requiredAlt, requiredWidth, requiredHeight },
}: RenderSlideProps) {
  return (
    <Image
      src={src}
      alt={requiredAlt}
      width={requiredWidth}
      height={requiredHeight}
    />
  );
}
```

```tsx
// App.tsx

<Lightbox
  slides={[
    {
	src: ...,
	requiredAlt: ...,
	requiredWidth: ...,
	requiredHeight: ...,
    },
  ]}
  render={{ slide: NextJsImage }}
  // ...
/>
```

2) Add custom slide type.

```tsx
// yet-another-react-lightbox.d.ts

import { GenericSlide } from "yet-another-react-lightbox";

declare module "yet-another-react-lightbox" {
  export interface CustomSlide extends GenericSlide {
    src: string;
    alt: string;
    width: number;
    height: number;
  }

  interface SlideTypes {
    "custom-slide": CustomSlide;
  }
}

export {};
```

```tsx
// NextJsImage.tsx

import Image from "next/image";
import type { CustomSlide, Slide } from "yet-another-react-lightbox";

export function isCustomSlide(slide: Slide): slide is CustomSlide {
  return slide.type === "custom-slide";
}

export default function NextJsImage({
  slide: { src, alt, width, height },
}: {
  slide: CustomSlide;
}) {
  return <Image src={src} alt={alt} width={width} height={height} />;
}
```

```tsx
// App.tsx

<Lightbox
  slides={[
    {
	type: "custom-slide",
	src: ...,
	alt: ...,
	width: ...,
	height: ...,
    },
  ]}
  render={{
    slide: ({ slide }) =>
	isCustomSlide(slide) ? <NextJsImage slide={slide} /> : undefined,
  }}
  // ...
/>
```

3) Provide default prop value even though it's not going to be the case in runtime.

```tsx
  alt={alt || ""} 
```

**Comment by ekeric13** [comment]
Okay yeah going with 1. Thanks!
