### ISSUE TITLE
Ability to set draggable and other html properties on default image slide

### ISSUE THREAD

**Issue by itwbaer** [igordanchenko/yet-another-react-lightbox#131]
### Is your feature request related to a problem? Please describe.

There is no way to set the `draggable` property of the `<img>` element of the default image slide component to something other than false. Our users are almost exclusively on desktop, and want the ability to drag photos onto their desktop to download them.

### Describe the solution you'd like

A property on the `SlideImage` type (or wherever else it makes sense) to set draggable, or better yet any of the standard html `<img>` props for the default image slide.

### Describe alternatives you've considered

Creating a custom image component and not using the default one

**Comment by igordanchenko** [comment]
The reason why `<img>` element has `draggable={false}` attribute is to allow click-and-drag gesture to swipe slides. 

However, here is what's going to happen if you set `draggable={true}`:
- click-and-drag navigation would no longer work if you click on the image itself
- click-and-drag navigation would still work if you click outside the image

Can you confirm this is the UX you want to achieve? You can test this behavior by changing the `draggable` attribute in the browser dev tools.

p.s. It's worth mentioning that there is a dedicated [Download](https://yet-another-react-lightbox.com/plugins/download) plugin that provides seamless download experience.

**Comment by itwbaer** [comment]
Thanks for the quick reply. Yes, I was able to test that and I see what you are talking about in terms of the click and drag behavior. 

This UX was requested by some of our users. The old lightbox we were using had draggable images, and evidently some users were saving images to their computers using this method. We speculate that most of them are clicking the arrows or using their keyboard to navigate, but need to gather some more data around that. The ability to spread props in to the image element would give us the ability to A/B test this, if nothing else.

I am going to add the Download plugin to our implementation as a workaround for now, thanks for suggesting that. We will also consider rolling our own image slide if this functionality doesn't get added.

I understand that this would allow people to use the default image slide in a way that is not really intended. Thanks for considering either way!

**Comment by igordanchenko** [comment]
OK, sounds good. I just wanted to make sure you are aware of the trade-offs. I'll add this configuration option shortly.

**Comment by igordanchenko** [comment]
```jsx
<Lightbox
  carousel={{ imageProps: { draggable: true } }}
  // ...
/>
```
