### ISSUE TITLE
YARL doesn't find CSS file if YARL opened in a NEXTJS sub layout.

### ISSUE THREAD

**Issue by Tcox-int** [igordanchenko/yet-another-react-lightbox#134]
### Describe the bug

I'm using YARL in a sup page layout:

/app
  /media
    page.js
    layout,js
    /screenshots
      page.js  <- HERE
      
When I use it, the YARL div opens properly, but devoid of any CSS.  When I hover over the div none of the classes are registering, so the div shows below all content on the page:

![image](https://github.com/igordanchenko/yet-another-react-lightbox/assets/131289343/37fd4e9d-f6cc-4d0a-bd74-4c823788e6e1)

If I go back to any of the 'main' pages and open YARL, the CSS shows up, and from that point on the CSS for the sub pages also loads:

![image](https://github.com/igordanchenko/yet-another-react-lightbox/assets/131289343/b525ed1e-cd72-484f-b623-1c98f320f697)

It also works if I take the CSS out of the Node Modules and plug is globally into my CSS file, but I am trying to avoid having to do that.

### Expected behavior

CSS for YARL loads regardless of where in the app structure it is used.

### How to reproduce

Place YARL in a sub-page APP directory layout in NEXTS 13.

### Screenshots / Logs

See above

**Comment by igordanchenko** [comment]
In which file are you currently importing the css? A code snippet or codesandbox would be of great help.

**Comment by Tcox-int** [comment]
In a file I wrote to handle lightbox interactions.

`'use client';

import { useEffect, useState } from 'react';
import { array, bool, func, number } from 'prop-types';

import Fullscreen from 'yet-another-react-lightbox/plugins/fullscreen';
import Lightbox from 'yet-another-react-lightbox';
import Thumbnails from 'yet-another-react-lightbox/plugins/thumbnails';
import Video from 'yet-another-react-lightbox/plugins/video';
import Zoom from 'yet-another-react-lightbox/plugins/zoom';
import 'yet-another-react-lightbox/plugins/thumbnails.css';

import { sizePhotos } from '/app/utils/lightbox';

const propTypes = {
  data: array.isRequired,
  photoNumber: number,
  navigation: bool,
  setPhotoNumber: func,
  thumbnails: bool,
};

const NextJsLightbox = ({
  data,
  photoNumber,
  navigation,
  setPhotoNumber,
  thumbnails,
}) => {
  const [photos, setPhotos] = useState([]);
  const handleOnClose = () => {
    setPhotoNumber(-1);
  };

  const nav = !navigation && {
    buttonPrev: photos.length <= 1 ? () => null : undefined,
    buttonNext: photos.length <= 1 ? () => null : undefined,
  };

  const plugins = thumbnails
    ? [Fullscreen, Thumbnails, Video, Zoom]
    : [Fullscreen, Video, Zoom];

  useEffect(() => {
    setPhotos(sizePhotos(data));
  }, [data]);

  return (
    <Lightbox
      close={handleOnClose}
      index={photoNumber}
      open={photoNumber >= 0}
      plugins={plugins}
      slides={photos}
      render={nav}
    />
  );
};

NextJsLightbox.propTypes = propTypes;

export default NextJsLightbox;`

**Comment by Tcox-int** [comment]
I'm just going to go ahead and move the css import to the base/home file.  Should solve the problem.

**Comment by igordanchenko** [comment]
Your original response didn't include the `import 'yet-another-react-lightbox/styles.css'`
Can you confirm you are actually importing it here?

**Comment by Tcox-int** [comment]
I was importing it at another location up the file structure before, but I just moved it.  Moving it seems to have solved the issue.  I am going to so some more testing, but so far relocating it seems to have helped.  Maybe where I had it before wasn't being called prior to this file. It should have been, but we all know how 'should' works.

**Comment by igordanchenko** [comment]
Well, that's exactly why I asked where exactly you are importing the css. If you are importing it in the `/app/page.js`, then it won't have any effect when you open `/screenshots` page.

**Comment by Tcox-int** [comment]
Hrm.  One would think it would given that the page is using the same layout?  But I guess not.   In any case, looks like it was just a mess up on my end.  Sorry for the hassle.

**Comment by igordanchenko** [comment]
You probably wanted to import it in the `/app/layout.js` (this is my best guess). Importing the css file in the `/app/page.js` affects only that specific page. For instance, you do not see the content of the home page when you open `/screenshots`, hence there is no imported css as well.

**Comment by Tcox-int** [comment]
Makes sense. Still getting the hang of NextJS.  Thanks for the assist.
