### ISSUE TITLE
[Thumbnail] ::before ::after gradient

### ISSUE THREAD

**Issue by t-h-e** [igordanchenko/yet-another-react-lightbox#14]
### Describe the bug

First of all, thank you very much for this awesome component as well as [react-photo-album](https://github.com/igordanchenko/react-photo-album) 😃 

If you change the backdrop color to be slightly opaque, I noticed that in the thumbnail container there is a gradient from on the left and right side.
I think there is no nice way to get ride of it. I added my own css to remove it.
Can this gradient be removed or be made configurable?

### Expected behavior

No gradient on the left and right of the thumbnail container, as you cannot even see the gradient with default settings.

### How to reproduce

```
<Lightbox
        slides={images}
        open={index >= 0}
        index={index}
        close={() => setIndex(-1)}
        controller={{ closeOnBackdropClick: true }}
        plugins={[Fullscreen, Slideshow, Thumbnails, Zoom]}
        styles={{
          root: { "--yarl__color_backdrop": "rgba(0, 0, 0, 0.3)" } as any,
        }}
      />
```
The `--yarl__color_backdrop` is set to be quite opaque so that the gradient is easy to spot.

Possible additional improvement: Can you add the variables that can be set in the `styles` to the type definition of `SlotStyles` to avoid the `any` cast in the code above?

### Screenshots / Logs

![image](https://user-images.githubusercontent.com/999552/183453037-084dda52-e1a9-4957-b090-2ade562a1731.png)

**Comment by igordanchenko** [comment]
Thanks for reporting this. I still haven't figured out how to overlay two gradients to achieve solid background color, so the best option for now is to hide these gradients when using semi-transparent backdrop color. I'll add a configuration option for this.

> Can you add the variables that can be set in the styles to the type definition of SlotStyles to avoid the any cast in the code above?

Sure. I'm not sure I want to hardcode all possible lightbox variables in the type declarations, so I'm going to add strings starting with "--yarl__":

```jsx
interface SlotCSSProperties extends React.CSSProperties {
    [key: `--yarl__${string}`]: string | number;
}
```

And btw, casting to `CSSProperties` was a better alternative to `any`:

```jsx
{ "--yarl__color_backdrop": "rgba(0, 0, 0, 0.3)" } as React.CSSProperties
```

**Comment by igordanchenko** [comment]
```jsx
<Lightbox
  thumbnails: { vignette: false }
/>
```

**Comment by t-h-e** [comment]
Thank you for the quick reponse.
Works like a charm 😃
