### ISSUE TITLE
Ability to include anchor element in description part of captions

### ISSUE THREAD

**Issue by memostar91** [igordanchenko/yet-another-react-lightbox#140]
### Is your feature request related to a problem? Please describe.

Not related to a problem

### Describe the solution you'd like

I'm using the package in my Next.js project and I'd like to be able to include an anchor element in the description part of the captions for each slide. Currently, it seems that the package doesn't provide a built-in way to do this.

Is it possible to add this functionality to the package? It would be very useful for my use case, and I imagine it could be useful for other users as well.

Thank you for your time and for maintaining this great package!

### Describe alternatives you've considered

I have tried to alter description value into a JSX element when i fetch the array of "slides" from an api endpoint. However, it just breaks the lightbox since it only accepts string.

**Comment by igordanchenko** [comment]
The library already supports JSX markup in the slide `title` and `description` props. Please also see #56 

If you require further assistance, please share a code snippet or sandbox showing what you're tried that didn't work.

**Comment by memostar91** [comment]
Yes, you are right. I should have searched better. I will try to make it fit into my use case.
