### ISSUE TITLE
Anyway to get current index from outside component or custom callback for prev/next buttons?

### ISSUE THREAD

**Issue by claritise** [igordanchenko/yet-another-react-lightbox#141]
### Is your feature request related to a problem? Please describe.

I want the index of the slide inside the lightbox to be reflected on my carousel in the page. Couldn't find anyway to do this in the documentation currently.

### Describe the solution you'd like

Any of these could work:
- Callback to set state inside the of the lightbox
- Lightbox index depends on state passed to it
- Allow custom callbacks on prev/next buttons

**Comment by igordanchenko** [comment]
Are you looking for something along these lines?

```jsx
const [index, setIndex] = React.useState(0);

<Lightbox
  index={index}
  on={{
    view: ({ index: currentIndex }) => setIndex(currentIndex),
  }}
  // ...
/>
```
