### ISSUE TITLE
Yarn build exits with error: Cannot divide by zero

### ISSUE THREAD

**Issue by zehawki** [igordanchenko/yet-another-react-lightbox#15]
### Describe the bug

Yarn build exits with error - on Netlify and local:

```
Cannot divide by zero
CompileError: Begins at CSS selector undefined
```

Since this was the only new library added after which build started failing, I started looking into what in particular in this library could be triggering this. I believe its these lines in styles.css where a divide by 0 is occurring:

```
.yarl__carousel {
  display: flex;
  flex: 0 0 auto;
  height: 100%;
  align-content: center;
  justify-content: center;
  align-items: stretch;
  width: calc(100% + (var(--yarl__carousel_slides_count, 0) - 1) * (100% + var(--yarl__carousel_spacing_px, 0) * 1px + var(--yarl__carousel_spacing_percent, 0) * 1%));
  -webkit-column-gap: calc(var(--yarl__carousel_spacing_px, 0) * 1px + 100 / (100 * var(--yarl__carousel_slides_count, 0) + (var(--yarl__carousel_slides_count, 0) - 1) * var(--yarl__carousel_spacing_percent, 0)) * var(--yarl__carousel_spacing_percent, 0) * 1%);
     -moz-column-gap: calc(var(--yarl__carousel_spacing_px, 0) * 1px + 100 / (100 * var(--yarl__carousel_slides_count, 0) + (var(--yarl__carousel_slides_count, 0) - 1) * var(--yarl__carousel_spacing_percent, 0)) * var(--yarl__carousel_spacing_percent, 0) * 1%);
          column-gap: calc(var(--yarl__carousel_spacing_px, 0) * 1px + 100 / (100 * var(--yarl__carousel_slides_count, 0) + (var(--yarl__carousel_slides_count, 0) - 1) * var(--yarl__carousel_spacing_percent, 0)) * var(--yarl__carousel_spacing_percent, 0) * 1%);
  -webkit-transform: translateX(var(--yarl__swipe_offset, 0px));
          transform: translateX(var(--yarl__swipe_offset, 0px));
}
.yarl__slide {
  flex: 1;
  position: relative;
  padding: calc(var(--yarl__carousel_padding_px, 0) * 1px + 100 / (100 * var(--yarl__carousel_slides_count, 0) + (var(--yarl__carousel_slides_count, 0) - 1) * var(--yarl__carousel_spacing_percent, 0)) * var(--yarl__carousel_padding_percent, 0) * 1%);
}
```
Commenting them makes build proceed just fine, as earlier.

### Expected behavior

Build should not crash.

### How to reproduce

Just a regular build.

**Comment by zehawki** [comment]
Sorry, forgot to mention that a small tweak of default values from 0 to 1 solves the compile issue. Though I'm not sure if this is fully correct:

```
  -webkit-column-gap: calc(var(--yarl__carousel_spacing_px, 0) * 1px + 100 / (100 * var(--yarl__carousel_slides_count, 1) + (var(--yarl__carousel_slides_count, 0) - 1) * var(--yarl__carousel_spacing_percent, 1)) * var(--yarl__carousel_spacing_percent, 1) * 1%);
     -moz-column-gap: calc(var(--yarl__carousel_spacing_px, 0) * 1px + 100 / (100 * var(--yarl__carousel_slides_count, 1) + (var(--yarl__carousel_slides_count, 0) - 1) * var(--yarl__carousel_spacing_percent, 1)) * var(--yarl__carousel_spacing_percent, 1) * 1%);
          column-gap: calc(var(--yarl__carousel_spacing_px, 0) * 1px + 100 / (100 * var(--yarl__carousel_slides_count, 1) + (var(--yarl__carousel_slides_count, 0) - 1) * var(--yarl__carousel_spacing_percent, 1)) * var(--yarl__carousel_spacing_percent, 1) * 1%);
```

`  padding: calc(var(--yarl__carousel_padding_px, 0) * 1px + 100 / (100 * var(--yarl__carousel_slides_count, 1) + (var(--yarl__carousel_slides_count, 0) - 1) * var(--yarl__carousel_spacing_percent, 1)) * var(--yarl__carousel_padding_percent, 1) * 1%);`

**Comment by igordanchenko** [comment]
What framework/bundler are you using? 

```jsx
<Lightbox open={open} close={() => setOpen(false)} slides={[]} carousel={{ spacing: 0, padding: 0 }} />

**Comment by igordanchenko** [comment]
Please let me know if v2.0.2 resolves your build error.

**Comment by zehawki** [comment]
>What framework/bundler are you using?

CRA 4.0.3
React 17
Node = v16.14.1
Yarn = v1.22.18

> Also, I do not see any errors in the browser.

Yup, there is no issue during development and nothing shows in browser. Only in build.

> Please let me know if v2.0.2 resolves your build error.

Sorry, still the same.

**Comment by igordanchenko** [comment]
> CRA 4.0.3
> React 17
> Node = v16.14.1
> Yarn = v1.22.18

Thank you for this. I didn't see this build error in CRA 5 as it's just logged as a warning in CRA 5.

Well, this is bonkers... Postcss minimizer plugin is trying to perform static analysis and minimize my css calc formulas without having any idea how the DOM is going to look like, how corresponding css classes are going to be used and what css var values might be... 

Removing the fallback values in css var() seems to do the trick though.

Let's give v2.0.3 a shot.

**Comment by zehawki** [comment]
> Let's give v2.0.3 a shot.

Thats just fine, thank you.

> Postcss minimizer plugin is trying to perform static analysis and minimize my css calc formulas without having any idea how the DOM is going to look like, how corresponding css classes are going to be used and what css var values might be...

Yup, exactly. Good thing that its a warning in CRA5.

> Removing the fallback values in css var() seems to do the trick though.

That's why I set the fallback values to 1, just so it would proceed without cribbing.
