### ISSUE TITLE
Lightbox does not apply overlay with black background

### ISSUE THREAD

**Issue by AlexString** [igordanchenko/yet-another-react-lightbox#163]
### Describe the bug

Lightbox does not apply overlay with black background and instead it renders at the bottom of the page.

I installed this package yesterday in version `^3.11.4`. 

I left it working like this:
![image](https://github.com/igordanchenko/yet-another-react-lightbox/assets/78276022/85ab2195-95b6-4a7d-aad3-4414e3727ef9)

This morning and without touching my commit I did yesterday (just running the project to see if it works), clicking on an image to view it looks like this:
![image](https://github.com/igordanchenko/yet-another-react-lightbox/assets/78276022/6f234759-ea54-4bfc-bf84-36cf9da4bfd1)

I have checked this in two browsers, Vivaldi and Firefox Dev Edition and both look the same.

### Expected behavior

Have overlay with black background like before

### How to reproduce

Just copied an Example and made it component, it worked perfectly yesterday

```typescript
import * as React from 'react'
// Lightbox
import Lightbox, { LightboxExternalProps } from "yet-another-react-lightbox";
import Captions from "yet-another-react-lightbox/plugins/captions";
import Fullscreen from "yet-another-react-lightbox/plugins/fullscreen";
import Slideshow from "yet-another-react-lightbox/plugins/slideshow";
import Thumbnails from "yet-another-react-lightbox/plugins/thumbnails";
import Video from "yet-another-react-lightbox/plugins/video";
import Zoom from "yet-another-react-lightbox/plugins/zoom";
import "yet-another-react-lightbox/plugins/captions.css";
import "yet-another-react-lightbox/plugins/thumbnails.css";

interface IPictureViewerProps {
	open: boolean;
	close: () => void;
	slides: LightboxExternalProps['slides']
}
const PictureViewer: React.FC<IPictureViewerProps> = ({
	open,
	close,
	slides
}) => {
	return (
		<Lightbox
			open={open}
			close={close}
			slides={slides}
			// zoom={{ maxZoomPixelRatio: 32 }}
			plugins={[Captions, Fullscreen, Slideshow, Thumbnails, Video, Zoom]}
		/>
	)
}

export default PictureViewer
```

### Additional context

Ignore the red rectangle that is on the zoom buttons, that was a screenshot from yesterday

**Comment by igordanchenko** [comment]
Duplicate #133
