### ISSUE TITLE
Close the lightbox when user clicks the browser back button

### ISSUE THREAD

**Issue by mhmdsalahsebai** [igordanchenko/yet-another-react-lightbox#164]
### Is your feature request related to a problem? Please describe.

When the lightbox is opened, and user clicks the browser back button, the browser navigate to the previous page.

### Describe the solution you'd like

I want to close the lightbox and stay on the same page rather than navigate to the previous page, I think this is the expected behaviour specially on the mobile.

**Comment by igordanchenko** [comment]
> When the lightbox is opened, and user clicks the browser back button, the browser navigate to the previous page.

This is the expected behavior.

> I want to close the lightbox and stay on the same page rather than navigate to the previous page, 

You are more than welcome to modify browser history state prior to opening the lightbox, but I do not believe the lightbox library should be messing around with browser history.

> I think this is the expected behaviour specially on the mobile.

Respectfully disagree.
