### ISSUE TITLE
Module level directives cause errors when bundled, "use client"

### ISSUE THREAD

**Issue by parth391** [igordanchenko/yet-another-react-lightbox#166]
### Describe the bug

`vite v4.4.7 building for production...
node_modules/yet-another-react-lightbox/dist/index.js (1:0) Module level directives cause errors when bundled, "use client" in "node_modules/yet-another-react-lightbox/dist/index.js" was ignored.`

### Expected behavior

Error should not come.

### How to reproduce

Version details 

react: v18.2.0
vite: v4.4.7
yet-another-react-lightbox: 3.12.0

Error is coming while running `npm run build`.

**Comment by igordanchenko** [comment]
First off, this is not an error, but merely a warning. You are seeing this warning because you are using an outdated version of `@vitejs/plugin-react`. Updating your `@vitejs/plugin-react` to v4 will make this warning go away.
