### ISSUE TITLE
How video support play youtube video directly

### ISSUE THREAD

**Issue by tianyingchun** [igordanchenko/yet-another-react-lightbox#167]
### Describe the bug

How video support play youtube video directly?

### Expected behavior

How video support play youtube video directly

should support youtube.com as well as youtu.be
Regular URLs: http://www.youtube.com/watch?v=xjS6SftYQaQ
Embeded URLs: http://www.youtube.com/embed/xjS6SftYQaQ
Playlist URLs: http://www.youtube.com/playlist?list=PLA60DCEB33156E51F OR http://www.youtube.com/watch?v=xjS6SftYQaQ&list=SPA60DCEB33156E51F
https://www.youtube.com/shorts/kzRNUu6EuqQ

### How to reproduce

Video Plugin

**Comment by igordanchenko** [comment]
Duplicate #49
