### ISSUE TITLE
Module not found npm/jest

### ISSUE THREAD

**Issue by Akiyele** [igordanchenko/yet-another-react-lightbox#168]
### Describe the bug

I have the same problem as described in https://github.com/igordanchenko/yet-another-react-lightbox/issues/7 , but i am using npm. 
The error message is "Cannot find module 'yet-another-react-lightbox' from 'LightboxSlider.js'".
It appears in the first import of the Lightbox modules.
```
import Lightbox from 'yet-another-react-lightbox';
import Captions from 'yet-another-react-lightbox/plugins/captions';
import Thumbnails from 'yet-another-react-lightbox/plugins/thumbnails';
import Video from 'yet-another-react-lightbox/plugins/video';
import Zoom from 'yet-another-react-lightbox/plugins/zoom';
import 'yet-another-react-lightbox/styles.css';
import 'yet-another-react-lightbox/plugins/captions.css';
```

When i change the import path to 'yet-another-react-lightbox/dist/index.js' i get another error message (shown in additional text).
Adding the transform option in my jest.config.js wasn't working.
```
  transform: {
    '^.+\\.(js|jsx|ts|tsx)$': ['babel-jest', { presets: ['next/babel'] }],
    '^.+\\.ts$': 'ts-jest',
  },
```

Thanks for any advice.
Best regards,
Stefan

### Expected behavior

Run jest tests including Lightbox with no errors

### How to reproduce

Tried different npm, node and lightbox versions.
Always had the same problem.
Even with the latest versions.
npm 9.8.1
node 18.17.0
lightbox 3.12.0

### Additional context

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    C:\Users\hupp\PhpstormProjects\headless\dug-react-storefront\node_modules\yet-another-react-lightbox\dist\index.d.ts:1
    import * as React from 'react';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

       7 | import { SideBySideMagnifier } from 'react-image-magnifiers';
       8 | // import Lightbox from 'yet-another-react-lightbox';
    >  9 | import Lightbox from 'yet-another-react-lightbox/dist/index.js';
         | ^

**Comment by igordanchenko** [comment]
Duplicate #148 

I don’t believe your issue is related to #7 since the errors in #7 were caused by outdated version of `react-scripts` (CRA 4). 

Please see https://github.com/igordanchenko/yet-another-react-lightbox/issues/148#issuecomment-1622788210 where you can find two working examples using jest.
