### ISSUE TITLE
Click and drag to move around causes unwanted zooming

### ISSUE THREAD

**Issue by JPVRS** [igordanchenko/yet-another-react-lightbox#169]
### Describe the bug

Basically what the title says. I have zoom enabled, and I want the functionality of zooming using the +/- icons or a single click on the image itself while using the viewer. But when I click and hold with the mouse to drag the image around (which I find to be a natural interaction), as soon as I let go of the mouse button, an unwanted zoom-in action occurs.

### Expected behavior

If I click and hold with the mouse to drag the image around, nothing should happen when I let go of the mouse button. Only single clicks should register as zoom-in actions.

### How to reproduce

Click and hold with the mouse to drag an image around while zoomed using the viewer.

**Comment by igordanchenko** [comment]
Are you experiencing this issue when browsing the [example](https://yet-another-react-lightbox.com/plugins/zoom) on the documentation website? So far, I'm unable to reproduce what you are describing.

**Comment by JPVRS** [comment]
With regard to this and the other issue I posted, which probably have the same root cause... I think this is specific to my setup. The example on the documentation website works fine regardless of whether I have single-click or double-click to open in my OS settings (Windows). I did need to check that because I use single-click which isn't the default.

So the issue is only happening my specific implementation. I'm using it in Next.js 13 with the pages directory (not app directory), with the MUI CSS framework, running on localhost in dev mode. I'm using it like this:

```
              <Box
                width="1"
                component="img"
                src={imageUrl}
                loading="lazy"
                onClick={() => setIsLightBoxOpen(true)}
              />

              <Lightbox
                open={isLightBoxOpen}
                close={() => setIsLightBoxOpen(false)}
                plugins={[Zoom]}
                zoom={{ ref: zoomRef }}
                on={{
                  click: () => zoomRef.current?.zoomIn(),
                }}
                slides={[
                  {
                    src: imageUrl,
                    alt: "Image Alt Text",
                  },
                ]}
                render={{
                  buttonPrev: () => null,
                  buttonNext: () => null,
                }}
              />
            </Box>
```

Does this information help at all?

**Comment by igordanchenko** [comment]
So here is the culprit:

```js
on={{
  click: () => zoomRef.current?.zoomIn(),
}}
```

> But when I click and hold with the mouse to drag the image around (which I find to be a natural interaction), as soon as I let go of the mouse button, an unwanted zoom-in action occurs.

You are literally telling the lightbox to zoom-in on mouse click :)

Honestly, I'm not sure it's a good idea to implement zoom-in gesture on a single mouse click. This is not something that is supported by the library, and as you can see it can conflict with other features / gestures.

**Comment by JPVRS** [comment]
That does make sense. I think I just pasted that from the example in the docs which is this:

return (
    <Lightbox
        plugins={[Zoom]}
        zoom={{ ref: zoomRef }}
        on={{
            click: () => zoomRef.current?.zoomIn(),
        }}
        // ...
    />
);

Maybe I'm confused though. Regardless, removing that portion did fix the issue, and it's working like the demo now. So problem solved.

Thank you very much for the help! I won't close in case there's anything to add, but feel free to do so.

**Comment by JPVRS** [comment]
No worries, thank you for clarifying. It's hard to complain when you've created such a useful and needed package for people to use!
