### ISSUE TITLE
Hide the navigation buttons when there is only one slide

### ISSUE THREAD

**Issue by varmints** [igordanchenko/yet-another-react-lightbox#17]
### Is your feature request related to a problem? Please describe.

Hide the navigation buttons when there is only one slide

### Describe the solution you'd like

Add an option to hide the navigation buttons

**Comment by igordanchenko** [comment]
I'm not inclined to add a separate option for this case, as one can easily achieve the desired behavior with the existing `render` prop.

```jsx
const renderNavigation = slides.length <= 1 ? () => null : undefined;

<Lightbox
  render={{ buttonPrev: renderNavigation, buttonNext: renderNavigation }}
/>
```

Here is the complete example - https://codesandbox.io/s/yet-another-react-lightbox-17-0gjlid?file=/src/App.js

**Comment by dingedi** [comment]
how to disable navigation if there are only 1 slide ?

**Comment by igordanchenko** [comment]
@dingedi, did you have a chance to take a look at the example provided above? I believe it answers your question.

**Comment by dingedi** [comment]
Thanks for your response i have disable icon like in the exemple but i didnt manage to disable navigation with keyboard

**Comment by igordanchenko** [comment]
You missed the `carousel.finite` setting. It's in the codesandbox example posted above.

**Comment by tiandengpan** [comment]
Very helpful
