### ISSUE TITLE
Single click to adjust zoom level including back to default view

### ISSUE THREAD

**Issue by JPVRS** [igordanchenko/yet-another-react-lightbox#170]
### Is your feature request related to a problem? Please describe.

If I single-click on the image while using the viewer, it zooms in. If I click again, it zooms in again. But if I click a third time, instead of looping back around to the default view, it doesn't respond. I don't know if this is a bug per se, so I've submitted it as a feature request. It definitely feels wrong to not be able to click again and get back to the default view, and instead have to move up to the icons for that.

### Describe the solution you'd like

I'd like to be able to click again and get back to the default view, and not have to move up to the icons for that. It would function like the pull-cord on a ceiling fan, where each time you pull the cord it changes the speed setting, and if you keep pulling, it will loop back around to the default (off).

### Additional context

Great package 👍

**Comment by igordanchenko** [comment]
> If I single-click on the image while using the viewer, it zooms in.

It shouldn't. The zoom-in mouse gesture is double-click, not a single click (well, this and ctrl + mouse wheel). Are you using some non-standard mouse configuration in your OS?

> I'd like to be able to click again and get back to the default view, and not have to move up to the icons for that. It would function like the pull-cord on a ceiling fan, where each time you pull the cord it changes the speed setting, and if you keep pulling, it will loop back around to the default (off).

This is how the lightbox actually works but with double-click / double-tap. Can you test on a different device?

**Comment by JPVRS** [comment]
Thank you for replying. I've commented in the other issue I posted and I'll close this one as a duplicate, since they appear to have the same root cause.
