### ISSUE TITLE
Changing images takes a while

### ISSUE THREAD

**Issue by parsagholipour** [igordanchenko/yet-another-react-lightbox#178]
### Describe the bug

I think this is related: https://stackoverflow.com/questions/50690956/react-img-not-immediately-changing-when-src-changes-how-can-i-fix-this
I'm using it as carousel and when I change the slides/images, src of the slide changes immediately but it shows the old image till the new image is loaded.

### Expected behavior

I'd like to show a loading while the new image is being loaded. Because I'm using it as a gallery in a page and when the user changes the gallery, he might get confused since the old image is still being shown for a while.

### How to reproduce

Change the slides prop. Also it's better to throttle your network.

**Comment by igordanchenko** [comment]
You should provide `key` attribute in this case, and change it alongside with the `slides` array.

**Comment by parsagholipour** [comment]
@igordanchenko Is there an event I can use to show a loading till the image is loaded.

**Comment by igordanchenko** [comment]
The loading spinner appears automatically 800ms after the image starts loading. If you prefer to display your own loading indicator, you can implement it via `render.iconLoading` render function.

```jsx
<Lightbox
  render={{ iconLoading: () => ... }}
  // ...
/>
```
