### ISSUE TITLE
Full Screen Lightbox scrolls page back to top on open

### ISSUE THREAD

**Issue by BogdanFalk** [igordanchenko/yet-another-react-lightbox#180]
### Describe the bug

Whenever I open an image into the full screen lightbox the page just scrolls to the top.

https://github.com/igordanchenko/yet-another-react-lightbox/assets/30993234/030e4bc5-3d48-4f52-b607-dc2060a3edd2

```
<Lightbox
            slides={uploadedImages.map((image) => {
              return !image.isDemoImage
                ? {
                    src: "https://storage.googleapis.com/${
                      import.meta.env.VITE_BUCKET_URL
                    }/${eventId}/${image._id}",
                  }
                : {
                    src: image._id,
                  };
            })}
            open={index >= 0}
            index={index}
            close={() => setIndex(-1)}
            reactModalProps={{ shouldReturnFocusAfterClose: true }}
            plugins={[Fullscreen, Slideshow, Thumbnails, Zoom]}
          />
```

### Expected behavior

Not to scroll anywhere keep the page at the scroll level it is.

### How to reproduce

Seems only replicable on my end I tested on the website and it doesn't seem to do that.

**Comment by BogdanFalk** [comment]
![image](https://github.com/igordanchenko/yet-another-react-lightbox/assets/30993234/368117aa-eae5-4bda-838b-3799bed52db9)
After some debugging I can tell that line 1324 from index.js "node.scrollTop" does the scrolling is there a prop that stops doing that, maybe I missed it.

**Comment by eloyra** [comment]
I have the same issue, please let me know if you manage to solve it. I'll do the same :raised_hands:

**Comment by igordanchenko** [comment]
@BogdanFalk @eloyra are you able to share a live demo or provide a sandbox with reproducible example?

**Comment by BogdanFalk** [comment]
Well I retried the with `void(node.offsetHeight);` and its the same I will try and create an example in sandbox today and post it here.

**Comment by eloyra** [comment]
I didn't have time to create an example yet, but after trying different stuff I'm no longer sure it's because of that line.

In my case it seems related to the `yarl__no_scroll` class that is added to the `body` when opening the lightbox. However, I got very erratic behavior when I tried to fix it.

If I add these CSS lines to my `body` directly, I no longer get the "scroll to top" error:
```css
  overflow: inherit !important;
  overscroll-behavior: inherit !important;
  height: 100% !important;
  padding-right: 0 !important;
```
However, if I try to override the `yarl__no_scroll` class or add my own (to apply said styles) at the same time, I get some erratic behavior like there is a race condition when adding the different styles, and it doesn't work all the time, it's very strange.

In any case, the issue seems related with the fact that by setting `overflow` to `hidden` you basically remove the the scrollbar and reset the scroll to the top.

**Comment by igordanchenko** [comment]
Thank you both for the updates! I think we are on the right track. When the lightbox opens, it adds the `yarl__no_scroll` class to the document `<body>` to hide the vertical scrollbar and prevent document body underneath the lightbox from scrolling on iOS. There is an escape hatch that lets you completely disable this functionality:

```jsx
<Lightbox
  plugins={[({ remove }) => remove("no-scroll")]}
  // ...
/>
```

However, I'd love to reproduce this issue on my end and come up with a proper fix.

Can you post your CSS styles that you apply to your `<html>` and `<body>` tags?

**Comment by eloyra** [comment]
I think this is everything being applied to the `html` and `body`.
![image](https://github.com/igordanchenko/yet-another-react-lightbox/assets/77033719/512fdb99-1829-4cc9-afb3-31d18aa0a8f6)
![image](https://github.com/igordanchenko/yet-another-react-lightbox/assets/77033719/d6b111c6-9919-4d43-b29d-26d7e973057d)

**Comment by igordanchenko** [comment]
Thank you for providing your CSS styles. I'm able to reproduce this issue now.

Can you please test the following [patch-package](https://www.npmjs.com/package/patch-package) patch and see if it resolves the issue in your case?

https://gist.github.com/igordanchenko/00e603c5c12014896f3ace8962899f55

**Comment by eloyra** [comment]
Thanks for the quick work! Very cool.
I'm on holidays this week, but I'll check it asap when I come back.

**Comment by eloyra** [comment]
@igordanchenko I was able to test your patch.
It looks like you are on the right track, and now the scroll position is preserved, however there is still something going wrong.

As you can see in the screenshots, there is a bad interaction with the header and sidebars, which is somewhat worse in the third screenshort, where you can see part of them on the top of the screen:
<details>
  <summary>
    <b>Screenshots</b>
  </summary>

![image](https://github.com/igordanchenko/yet-another-react-lightbox/assets/77033719/00c973fa-e0d2-4da6-a0f2-2df6afe76970)
![image](https://github.com/igordanchenko/yet-another-react-lightbox/assets/77033719/b06ce1dd-a908-4bda-9c85-0a8c6adb991d)
![image](https://github.com/igordanchenko/yet-another-react-lightbox/assets/77033719/13c06f70-178d-4c91-9b82-5c74252f543f)
</details>

They are all `sticky` elements, so that's probably the issue.

<details>
  <summary>
    <b>CSS</b>
  </summary>

  The left sidebar styles:
```css
    position: sticky;
    top: 0;
    display: flex;
    flex-direction: column;
    width: var(--sidebar-width-open);
    min-height: 100vh;
    background: #151719;
    box-shadow: inset -1px 0 0 #383d42;
```

The right sidebar styles:
```css
    top: var(--desktop-header-height);
    height: calc(100dvh - var(--desktop-header-height) - 1px);
    position: sticky;
    border-left: 1px solid #383d42;
```

The header styles:
```css
    position: sticky;
    top: 0;
    z-index: 6;
    -webkit-backdrop-filter: blur(5px);
    backdrop-filter: blur(5px);
```
</details>

Let me know if I can do anything else to help.

**Comment by igordanchenko** [comment]
@eloyra thank you for testing the patch and following up.

> Let me know if I can do anything else to help.

To eliminate the guesswork on my side, do you mind creating an isolated demo on codesandbox.io that replicates your layout? That would help a lot.

**Comment by eloyra** [comment]
Sure, it might take me a few days to find the time, but I'll get it done.

**Comment by igordanchenko** [comment]
@eloyra as you pointed out, there are additional issues with `sticky` elements, and fixing their position seems too intrusive within the scope of this library. With that being said, I'm not inclined to proceed with the above patch.

At this point, I can suggest the following solutions to the original issue:

1) Disable the `no-scroll` module with `plugins={[({ remove }) => remove("no-scroll")]}` (I'll probably add a config option to make it more straightforward)

2) Get rid of the `html, body { height: 100% }` as some sources recommend

https://greggod.medium.com/css-do-not-put-height-100-on-the-body-html-e36bda3551b3

and replace with either 

```css
body {
  min-height: 100vh;
  min-height: 100dvh;
}
```

or 

```css
html {
    min-height: 100%;
    display: flex;
    flex-direction: column;
}

body {
    flex-grow: 1;
}
```

https://dev.to/fenok/stretching-body-to-full-viewport-height-the-missing-way-2ghd

**Comment by igordanchenko** [comment]
@BogdanFalk please let me know if you have any feedback

**Comment by eloyra** [comment]
Hello there @igordanchenko!

I'm so sorry that I never got around to that Sandbox, and the latest replies got lost in mail.
I've updated the code to use the new configuration option, works great :muscle: 
I've also explored the two approaches you suggest and they made no change whatsoever relative to our current CSS setup, but they were interesting reads nontheless, thanks for the suggestions.

**Comment by igordanchenko** [comment]
Thank you for the feedback @eloyra

**Comment by gabrielvieiraes** [comment]
I have the same problem, I tried the fixes mentioned here, but sometimes the screen scrolls to the top when I open the image.

This is my component. I'm using MantineUI.
"react": "^16.12.0"
"yet-another-react-lightbox": "^3.15.5"
"mobx": "^5.15.0",
"mobx-react": "^6.1.4",

const GallerySection = observer(({ imagens, identificador }: GallerySectionProps) => {
  const { classes, theme } = useStyles();
  const [index, setIndex] = React.useState(-1);
 const slides = imagens.map((photo: LandpageGaleriaDadosDto) => {
    return {
      src: photo.linkImagem,
      title: photo.legenda,
    };
  });

  return (
    <>
      <Container id={identificador} size="xl" py="xl">
        <Title order={2} className={classes.title} align="center" mt="sm">
          Galeria
        </Title>

        <SimpleGrid
          cols={3}
          mt={50}
          breakpoints={[
            { maxWidth: '62rem', cols: 3 },
            { maxWidth: '48rem', cols: 2 },
            { maxWidth: '36rem', cols: 1 },
          ]}
        >
          <GalleryCards
            imagens={imagens}
            setIndex={(i: number) => {
              setIndex(i);
            }}
          />
        </SimpleGrid>

        <Lightbox
          noScroll={{ disabled: true }}
          plugins={[Captions]}
          index={index}
          slides={slides}
          open={index >= 0}
          close={() => setIndex(-1)}
        />
      </Container>
    </>
  );
});
