### ISSUE TITLE
Thumbnails plugin: display a minimum number of thumbnails / show all thumbnails

### ISSUE THREAD

**Issue by philibere** [igordanchenko/yet-another-react-lightbox#185]
### Is your feature request related to a problem? Please describe.

When the number of slides is small and the current slide is the first or the last one, the thumbnails track does not show all the available thumbnails.

The first slide is active (1/3):
![image](https://github.com/igordanchenko/yet-another-react-lightbox/assets/145703570/634b6177-337b-4bf6-b1c5-c9fa3d24b143)

The second slide is active (2/3):
![image](https://github.com/igordanchenko/yet-another-react-lightbox/assets/145703570/8cab69f5-78aa-4672-8212-adff1b32c0bc)

The last slide is active (3/3):
![image](https://github.com/igordanchenko/yet-another-react-lightbox/assets/145703570/16c3ba08-48e4-4263-bb46-70f65b6d7268)

In the file: **src/plugins/thumbnails/ThumbnailsTrack.tsx,** line **90**:

` const preload = Math.min(carousel.preload, Math.floor(slides.length / 2));`

In my example above, my carousel has a preload value of 10 and 3 slides, so Math.floor(slides.length/2) equals 1. When the first slide is active, only the second thumbnail is displayed.

### Describe the solution you'd like

Add a prop to set the minimum number of thumbnails displayed at all time AND/OR add a boolean prop to specify is all the thumbnails must me displayed or not.

**Comment by igordanchenko** [comment]
I'm assuming you are using `finite: true` setting. If that's the case then it looks like a bug. I'll take a closer look at this case in the following days and will provide a solution soon.

**Comment by philibere** [comment]
Yes, here are the carousel parameters I use:

`carousel={{ finite: true, preload: 10, padding: 0, imageFit: 'contain' }}`

And the thumbnail plugin parameters:

`thumbnails={{
          position: 'bottom',
          width: 40,
          height: 40,
          imageFit: 'contain',
          vignette: false,
          ref: thumbnailsRef,
          border: 0,
        }}`

Hope that helps!
