### ISSUE TITLE
Open fullscreen on image click

### ISSUE THREAD

**Issue by oleg-andreyev** [igordanchenko/yet-another-react-lightbox#19]
### Is your feature request related to a problem? Please describe.

It would be great to have the ability to toggle the fullscreen mode on image click, not on the "fullscreen image" icon.

### Describe the solution you'd like

Fullscreen mode is triggered by clicking on the "main image" (same as the "fullscreen" icon works)

**Comment by igordanchenko** [comment]
Here is the user-land implementation - https://codesandbox.io/s/yet-another-react-lightbox-19-4z1ips?file=/src/App.js

Demo - https://4z1ips.csb.app
