### ISSUE TITLE
Add offsetX and offsetY in zoomIn/Out function

### ISSUE THREAD

**Issue by xAlban** [igordanchenko/yet-another-react-lightbox#195]
### Is your feature request related to a problem? Please describe.

Hello,
First, thanks for keeping this library updated !

I have a need of zooming on a particular area conditionally (= I need to call a method to trigger this feature).

### Describe the solution you'd like

I saw in the zoom plugin code that you already have the method handling the zoom with those offset (changeZoom method). And this behavior is already implemented when you zoom with the mouse (the zoom goes where the mouse pointer).

Is it possible to expose those offsets in the zoomIn/zoomOut method as optionnal parameters ? (zoomValue, dx, dy)

Thanks in advance !

**Comment by igordanchenko** [comment]
Hi there! Can you test the following patch-package patch and confirm that `changeZoom` method is working as expected in your use case?

https://gist.github.com/igordanchenko/f40ffea9c4fc281b6d00c46cd8f2d3a2

I just want to make sure it's going to meet your expectations before I expose this method publicly.

**Comment by xAlban** [comment]
Hi Igor,

I can't use the patch-package at the moment (and never used it actually 😅 ). But I checked the gist and it's exactly what I need !

Please let me know when the method is available publicly.

Thanks a lot !
