### ISSUE TITLE
Closing lightbox shifts focus to the top of page

### ISSUE THREAD

**Issue by Tcox-int** [igordanchenko/yet-another-react-lightbox#199]
### Describe the bug

I am trying to make a keyboard accessible implementation of the gallery.  I have everything working save for one thing, when I close the selected image using the escape key it seems the focus and tabIndex is reset back to the top of the page so I am unable to tab to the next image, it just goes back to the top of the page.

Is this a known issue? Are there any workarounds?  I've tried to programmatically apply focus back to the image when it closes, but that didn't appear to work.  Any help would be appreciated. 

### Expected behavior

When you use keyboard and tab to an image then open it, you should be able to use esc to close the lightbox and tab to the next image.

### How to reproduce

Make a gallery of images.  
Tab to an image and select it.
Press escape
Hit tab. Notice that the focus/tabindex starts over again and you have to tab all the way back down.

**Comment by Tcox-int** [comment]
Sorry.  I missed the focus call on the controller, but just saw it again as I went through the documentation again.  I think that is likely my problem.

I'll close this out and reopen if I still have issues.

**Comment by Tcox-int** [comment]
I thought Focus might help in the controller, but that just brings focus to the lightbox when it it opened, does nothing to retain focus back when the lightbox is closed.

**Comment by igordanchenko** [comment]
Thank you for pointing out this usability issue.

**Comment by Tcox-int** [comment]
Thank you so much!
