### ISSUE TITLE
Type 'boolean is not assignable to 'never'

### ISSUE THREAD

**Issue by FluidSense** [igordanchenko/yet-another-react-lightbox#2]
### Describe the bug

Hey 👋 and thanks a lot for yet-another-great-package!
react-photo-album was perfect for my usage, and now a lightbox on top was just what I wanted!

However, after copying your example, I get TypeScript complains on all props.

With a simple //@ts-ignore before any prop, everything works as expected!

### Expected behavior

Types to be understood correctly by `tsc` and give warnings when they are wrong

### How to reproduce

1. npm install yet-another-react-lightbox@1.2.0 in a ts-based project
2. Import { Lightbox } from "yet-another-react-lightbox"
3. Try to use it in render and add props
4. See faulty types

### Screenshots / Logs

<img width="522" alt="image" src="https://user-images.githubusercontent.com/22146437/170828533-e470a1b3-2145-4067-bd47-e8a135f10ab6.png">

Lightbox's listed types
<img width="968" alt="image" src="https://user-images.githubusercontent.com/22146437/170828787-a91404e1-f443-458f-93e7-715f57f9e6fc.png">

**Comment by igordanchenko** [comment]
Hi! Thank you for reporting this issue. What version of TypeScript are you using?

**Comment by igordanchenko** [comment]
Just a quick update here. I tried reproducing this issue but haven't been successful so far. I tried downgrading to React 17 and TypeScript all the way down to 3.9, but in all my tests `tsc` type checks just fine. Can you provide some additional details about your project environment?

```
node -v
npm ls --depth=0 react react-dom @types/react @types/react-dom typescript
cat tsconfig.json
```

Also, do you see this error in `tsc` output or just in the IDE?

**Comment by FluidSense** [comment]
Thanks for checking it out!

I get the error both in VSCode and through `tsc`.

#### Node version
`v18.0.0`

#### TypeScript version
`Version 4.5.2`

#### Other packages
Output of `npm ls --depth=0 react react-dom prop-types @types/react @types/react-dom @types/node typescript`: 

<img width="207" alt="image" src="https://user-images.githubusercontent.com/22146437/170867504-8972f80b-e3b7-4434-a28a-b254a9b9bed9.png">


#### TSConfig
```{
  "compilerOptions": {
    "target": "esnext",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "moduleResolution": "node",
    "baseUrl": "./"
  },
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx"
, "components/NewDesign"  ],
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by igordanchenko** [comment]
Thank you! Can you also tell me your prop-types version?

```
npm ls prop-types
```

**Comment by FluidSense** [comment]
> Thank you! Can you also tell me your prop-types version?
> 
> ```
> npm ls prop-types
> ```

Sure! It is `15.8.1`

<img width="402" alt="image" src="https://user-images.githubusercontent.com/22146437/170873679-944144f0-8a44-45d5-9fc3-6c9783a4f6c8.png">

**Comment by igordanchenko** [comment]
I was finally able to reproduce it! Changing `strict` to `true` in `tsconfig.json` solved the issue.

```
"strict": true,
```

Let me dig into why this is happening when `strict` is set to `false`...

**Comment by igordanchenko** [comment]
Fixed in v1.2.3

**Comment by FluidSense** [comment]
v1.2.3 works like a charm! Thank you so much for fixing it so fast!

**Comment by igordanchenko** [comment]
My pleasure!
