### ISSUE TITLE
TypeError: React.createContext is not a function

### ISSUE THREAD

**Issue by liuhe2020** [igordanchenko/yet-another-react-lightbox#20]
### Describe the bug

Server Error
TypeError: React.createContext is not a function

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
file:///home/liu/Projects/Github-Hypnosis-Events/node_modules/yet-another-react-lightbox/dist/core/contexts/Events.js (3:29)
ModuleJob.run
internal/modules/esm/module_job.js (138:23)
async Loader.import
internal/modules/esm/loader.js (178:24)

### Expected behavior

Plug and play

### How to reproduce

Not sure, all I did was install the package, use code from example. Then I get this error.

**Comment by igordanchenko** [comment]
Can you describe your environment?

```shell
node -v
tsc -v
npm ls --depth=0 react react-dom @types/react @types/react-dom @types/node typescript
cat tsconfig.json
```

**Comment by igordanchenko** [comment]
Updating your node version will solve this error. Your are using node v14.4.0, which is pre-LTS version. The first LTS version in the v14 release was v14.15.0.

I'd recommend updating to either v14.20.0 or v16.17.0

**Comment by liuhe2020** [comment]
Great, many thanks for your time for this resolution and for making this amazing package!
