### ISSUE TITLE
Next.js  with Thumbnails throws warning when changing images relatively faster

### ISSUE THREAD

**Issue by ms94ap** [igordanchenko/yet-another-react-lightbox#201]
### Describe the bug

When changing images fast the warning appears. If you change images slower the warning doesn't show up.

### Expected behavior

Not to receive the warning when changing images fast.

### How to reproduce

```jsx
<Lightbox
  open={open}
  close={() => setOpen(false)}
  slides={images}
  render={{ slide: NextJsImage, thumbnail: NextJsImage }}
  plugins={[Thumbnails]}
/>
```

### Screenshots / Logs

![Screenshot from 2023-11-07 18-53-52](https://github.com/igordanchenko/yet-another-react-lightbox/assets/17708770/514f199d-6c77-4230-8fe1-9a595a1a9dc3)

**Comment by igordanchenko** [comment]
Please provide a complete reproducible example.

**Comment by igordanchenko** [comment]
Never mind, I was able to reproduce this error.
