### ISSUE TITLE
Hiding Navigation Buttons not working

### ISSUE THREAD

**Issue by eduardodomingos** [igordanchenko/yet-another-react-lightbox#206]
### Describe the bug

Passing buttonPrev and buttonNext as null is not preventing them to be rendered.

### Expected behavior

Hide navigation buttons if passed as null.

### How to reproduce

```jsx
<Lightbox
  open={lightboxIsOpen}
  close={() => {
    setLightboxIsOpen(!lightboxIsOpen)
    lightboxId && document.body.classList.remove(`lightbox-${lightboxId}-is-open`)
  }}
  slides={[
    { src: picture.urlOriginal }
  ]}
  carousel={{ finite: true }}
  render={{
    buttonPrev: null,
    buttonNext: null,
  }}
/>
```

**Comment by igordanchenko** [comment]
You are supplying invalid values for the `buttonPrev` and `buttonNext` props. 

To hide the navigation buttons, you are supposed to **provide a function** returning `null` in the `buttonPrev` and `buttonNext` render props

```jsx
render={{
  buttonPrev: () => null,
  buttonNext: () => null,
}}
```

https://yet-another-react-lightbox.com/customization#HidingNavigationButtons
