### ISSUE TITLE
Thumbnail fading animation broken when controlling the index

### ISSUE THREAD

**Issue by joshkay** [igordanchenko/yet-another-react-lightbox#212]
### Describe the bug

When passing a controlled index prop and updating it with the on prop view callback, the thumbnails flicker in and out when scrolling.

### Expected behavior

Same fade should occur as uncontrolled variant.

### How to reproduce

https://codesandbox.io/p/devbox/yet-another-react-lightbox-examples-forked-wm6fvt?initialpath=%2Fexamples%2Fbasic&file=%2Fsrc%2Fexamples%2FThumbnailsPlugin.tsx%3A49%2C24

**Comment by igordanchenko** [comment]
Thank you for the detailed bug report.
