### ISSUE TITLE
Importing Zoom plugin causes errors

### ISSUE THREAD

**Issue by JPVRS** [igordanchenko/yet-another-react-lightbox#219]
### Describe the bug

I'm running into an issue in this component. It's imported into a parent component which in turn is imported into a page. The page uses getServerSideProps to set some initial values and those are immediately read into state on the initial page load, and managed in state from that point forward.

Importing the Lightbox and the Zoom plugin as shown in the docs isn't working for me:

```
import Lightbox from "yet-another-react-lightbox";
import Zoom from "yet-another-react-lightbox/plugins/zoom";
import "yet-another-react-lightbox/styles.css";
```

If I try to import the Zoom plugin normally, I get a "getStaticPaths is not a function" error. The parent-parent page doesn't use getStaticPaths. If I try to import the Zoom plugin using a dynamic import, I get a "plugin is not a function" error. If I remove the Zoom plugin entirely, and also dynamically import the Lightbox, then it works. But of course, then the user can't zoom.

```
import { useState, useEffect, useRef } from "react";
import { Alert, AlertTitle, Card, Skeleton, Stack } from "@mui/material";
// import Zoom from "yet-another-react-lightbox/plugins/zoom";
import "yet-another-react-lightbox/styles.css";
import { logError } from "@lib/logError";

import dynamic from "next/dynamic";
const Lightbox = dynamic(
  () => import("yet-another-react-lightbox").then((mod) => mod.default),
  { ssr: false }
);

function Component({
  currentItemData,
  isCurrentItemDataLoading,
}) {
  const [isDataLoading, setIsDataLoading] = useState(true);
  const [isLightBoxOpen, setIsLightBoxOpen] = useState(false);
  // const zoomRef = useRef(null);

  useEffect(() => {
    // Set loading state based only on isCurrentItemDataLoading
    setIsDataLoading(isCurrentItemDataLoading);

    if (!isCurrentItemDataLoading) {
      if (
          ...
        ) {
        setIsDataLoading(false);
      } else {
        logError(new Error("Error text"), {
          ...
        });
        // router.push("/404");
        setIsDataLoading(false);
      }
    }
  }, [isCurrentItemDataLoading, currentItemData]);

  // Render Loading State
  const renderLoadingState = () => (
    ...
  );

  // If data is loading, render the loading state
  if (isDataLoading) {
    return renderLoadingState();
  }

  // Otherwise, continue
  const { imageUrl } = currentItemData;

  return (
    <>
      ...
      <Lightbox
        open={isLightBoxOpen}
        close={() => setIsLightBoxOpen(false)}
        // plugins={[Zoom]}
        // zoom={{ ref: zoomRef }}
        slides={[
          {
            src: imageUrl,
            alt: "Alt text",
          },
        ]}
        render={{
          buttonPrev: () => null,
          buttonNext: () => null,
        }}
      />
    </>
  );
}

export default Component;

```

In the code above, I've dynamically imported the Lightbox and commented out anything to do with the Zoom plugin. This is the only way I can get anything to work.

Any help would be appreciated. TIA.

### Expected behavior

The lightbox and zoom plugin should work without errors.

### How to reproduce

I've attached what I believe to be the relevant portions of code.

**Comment by igordanchenko** [comment]
Can you share an isolated [sandbox](https://codesandbox.io) demonstrating the issue? 

I highly suspect the issue you are experiencing is specific to your project / environment. Normally, dynamic imports aren't needed at all to use this library in SSR (unless you are specifically optimizing your bundle size).

**Comment by JPVRS** [comment]
I can do that if needed. It seems like it will take up a lot of time, although I understand it might be needed to get to the bottom of the issue.

Assuming it's an issue with my project / environment, how would I even start to investigate that?

I have other pages in my project where I use the Lightbox and Zoom plugin (both imported normally) without similar issues.

**Comment by JPVRS** [comment]
I don't know what happened, but suddenly it's working. Sorry to take up your time with this.

**Comment by igordanchenko** [comment]
Were you able to get rid of dynamic imports as well?

**Comment by JPVRS** [comment]
Yes, I was. At the moment it's working completely as I would expect. I don't understand it, but I must have knocked something loose somehow.

**Comment by igordanchenko** [comment]
Glad to hear it's working as expected now.
