### ISSUE TITLE
<picture> support

### ISSUE THREAD

**Issue by jkk** [igordanchenko/yet-another-react-lightbox#22]
### Is your feature request related to a problem? Please describe.

Thanks for your excellent library!

It would be great to be able to use the `<picture>` element instead of only `<img>`. My use case is to serve .webp images to most users but have a fallback to .jpg.

I was able to do this easily with `react-photo-album` by passing the `renderPhoto` prop. There's no direct equivalent in YARL. `render.slide` would require copying/recreating everything in ImageSlide, which is not ideal.

### Describe the solution you'd like

Simplest solution would be a `render.slideImage` callback for rendering just the `<img>`, not the entire ImageSlide component.

Another possibility is adding an optional `type` key to the `srcSet` array:

```js
[
  { src: "example-300.jpg", width: 300, height: 600, type: "image/jpeg" },
  { src: "example-600.jpg", width: 600, height: 1200, type: "image/jpeg" },
  { src: "example-300.webp", width: 300, height: 600, type: "image/webp" },
  { src: "example-600.webp", width: 600, height: 1200, type: "image/webp" }
]
```

Which would then render a `<picture>` with two `<source>` children and an `<img>` fallback (could default to the jpeg image, or add another key to indicate which should be the fallback).

### Describe alternatives you've considered

Using the `render.slide` option mentioned above (not ideal)

### Additional context

Here's the renderPhoto implementation I'm using for `react-photo-album`:

```js
function replaceWebpExtensions(imageUrl: string) {
  return imageUrl.replace(/(_jpg\.webp|\.webp)/g, ".jpg");
}

const renderPhoto: RenderPhoto = ({ imageProps }) => {
  let { src, alt, srcSet, sizes, ...restImageProps } = imageProps;
  let isWebp = src.endsWith(".webp");
  if (!isWebp) {
    return (
      // eslint-disable-next-line
      <img
        src={src}
        alt={alt}
        {...(srcSet ? { srcSet, sizes } : null)}
        {...restImageProps}
      />
    );
  }

  return (
    <picture>
      <source
        src={src}
        {...(srcSet ? { srcSet, sizes } : null)}
        type="image/webp"
      />
      <source
        src={replaceWebpExtensions(src)}
        {...(srcSet ? { srcSet: replaceWebpExtensions(srcSet), sizes } : null)}
        type="image/jpeg"
      />
      {/* eslint-disable-next-line */}
      <img
        src={replaceWebpExtensions(src)}
        alt={alt}
        {...restImageProps}
        loading="lazy"
      />
    </picture>
  );  
};
```

**Comment by igordanchenko** [comment]
Have you considered checking for .webp support prior to rendering the lightbox?

```js
const webp = e => document.createElement('canvas').toDataURL('image/webp').indexOf('data:image/webp') == 0;
```

Since YARL is a client-side-only component, it should be relatively easy to determine whether the browser supports a specific image format and pass the appropriate one to the lightbox.

**Comment by jkk** [comment]
@igordanchenko thanks for the quick reply! That's a good workaround. I'm using SSR for react-photo-album but you are correct that it's not needed for YARL.

It would still be nice to have a `renderImage` callback (I expected to find that when looking in the docs, and would be nice to share implementation with RPA), but your webp check is good enough for me to solve the immediate problem.

Feel free to close if you don't feel this feature is necessary.

**Comment by jkk** [comment]
@igordanchenko my understanding is that the `<img>` element inside `<picture>` behaves exactly the same as a plain `<img>`, i.e. attributes like `alt` and `onLoad` work the same. Only src is swapped. The `<picture>` container is merely semantic.

As far as `ref`, the callback could pass along the ref to the underlying img. For cases where the caller wants to render some other element (NOT an img), that could cause complication. You could throw an error if the ref is missing or not instanceof  HTMLImageElement.

Unfortunately I have limited time to work on this. I already have a working implementation based on your webp check, so my problem is solved. I might have time to run some more tests in the future, but can't make any promises. No hard feelings if you feel the implementation complexity isn't worth it.

**Comment by igordanchenko** [comment]
I completely understand, and I will close this for now since your use case has been addressed. 

> my understanding is that the `<img>` element inside `<picture>` behaves exactly the same as a plain `<img>`, i.e. attributes like `alt` and `onLoad` work the same. Only src is swapped. The `<picture>` container is merely semantic.

> As far as `ref`, the callback could pass along the ref to the underlying img. For cases where the caller wants to render some other element (NOT an img), that could cause complication. You could throw an error if the ref is missing or not instanceof HTMLImageElement.

I did a quick test with picture/source/img, and it looks like `<img>` element's `ref`, `onLoad`, and `onError` callbacks behave the same way as in a standalone `<img>` element. Good to know!

I will be open to implementing `<picture>` support (most likely as a plugin) to support the art direction use case (displaying different images depending on viewport size). To future visitors: please feel free to open a new ticket and describe your desired implementation (I'm sure I'll have some follow-up questions). I want to tailor my implementation to at least one real-life scenario.
