### ISSUE TITLE
inert=true is not being removed when Lightbox is unmounted

### ISSUE THREAD

**Issue by hzrd149** [igordanchenko/yet-another-react-lightbox#221]
### Describe the bug

I am using the `<Lightbox>` component in to display gallery images. and I'm using a custom `slideContainer` to add some extra information to the image along with a link to the users profile.

When the user clicks this link the app will change views **without** closing the lightbox. Unfortunately the lightbox is not removing the `inert="true"` attribute from the root so the page gets "frozen"

### Expected behavior

The lightbox should remove the `inert="true"` and `aria-hidden="true"` attributes from the root when unmounted

### How to reproduce

1. Create a simple app that renders the `Lightbox` component
2. Open the lightbox
3. Make the app unmount the lightbox without the user closing it

### Additional context

Thanks for making a react lightbox component that actually works and isn't built on jQuery

**Comment by igordanchenko** [comment]
What version of the lightbox are you using?

**Comment by igordanchenko** [comment]
The issue you are describing sounds like #209. Please upgrade the lightbox to the latest version and see if it resolves your issue.

**Comment by hzrd149** [comment]
I was using `3.12.1` and tried to upgrade to the latest but was still getting the issue.
I tried it again (this time with removing node_modules / lock file) and the issue seems to be resolved. I guess when I upgraded it did not pull in the latest version

Thanks for responding so quickly and sorry for wasting your time

**Comment by igordanchenko** [comment]
Thank you for confirming the latest version addresses your issue. That bug actually affected versions 3.15.0 through 3.15.3. I suspect your package.json contained a dependency on `^3.12.1`, but your lock file was actually pinned to one of the affected versions.
