### ISSUE TITLE
Inline plugin with custom slide does not open full sized lightbox 

### ISSUE THREAD

**Issue by ygor-infotera** [igordanchenko/yet-another-react-lightbox#234]
### Describe the bug

When I click in the image, it does not open the lightbox 

```ts
interface Props extends Omit<ImageProps, "src" | "width" | "height"> {
  images: LightboxImages;
  fallbackImage?: FallbackImage;
  noSwipe?: boolean;
}

const ImageLightbox: FC<Props> = ({
  className,
  images,
  noSwipe,
  loading,
  priority,
  ...props
}) => {
  const { setOpen, open, renderLightbox } = useLightbox();
  const [index, setIndex] = useState(0);
  const imagesLength = (images?.length ?? 0) - 1;
  const updateIndex = ({ index: current }: { index: number }) =>
    setIndex(current);

  return (
    <>
      <div
        className="relative w-full cursor-pointer transition-all duration-200 hover:brightness-90"
      >
        <Lightbox
          index={index}
          slides={images}
          plugins={[Inline]}
          on={{
            view: updateIndex,
            click: () => {
			// never gets called
              setOpen(true);
            },
          }}
          open={open}
          carousel={{
            imageProps: {
              className: cn(className),
            },
          }}
          inline={{ className: className }}
          render={{
            slide: CustomInlineSlide,
          }}
        />
      </div>
      {open && renderLightbox({ slides: images, index: index, setIndex })}
    </>
  );
};
```

The custom slide is almost a one to one copy of the custom Next.js slide example, useLightbox is not too different either.

### Expected behavior

To open the image in full size when I click it.

### How to reproduce

[Codesandbox](https://codesandbox.io/p/devbox/yet-another-react-lightbox-nextjs-ts-forked-p7r8hg?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrqo2sr400072v6hwukn75wz%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrqo2sr300022v6h3lublc37%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrqo2sr300042v6hpovl9u2t%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrqo2sr400062v6hq88ek6hw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrqo2sr300022v6h3lublc37%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrqo2sr300012v6hmgg9i3iu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clrqo2sr300022v6h3lublc37%2522%252C%2522activeTabId%2522%253A%2522clrqo2sr300012v6hmgg9i3iu%2522%257D%252C%2522clrqo2sr400062v6hq88ek6hw%2522%253A%257B%2522id%2522%253A%2522clrqo2sr400062v6hq88ek6hw%2522%252C%2522activeTabId%2522%253A%2522clrqo2sr400052v6hpel22hlh%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrqo2sr400052v6hpel22hlh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3001%252C%2522id%2522%253A%2522clrza75ns008h2v6mgkol0k9x%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clrqo2sr300042v6hpovl9u2t%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrqo2sr300032v6hf7vgpoz1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clrqo2sr300042v6hpovl9u2t%2522%252C%2522activeTabId%2522%253A%2522clrqo2sr300032v6hf7vgpoz1%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by igordanchenko** [comment]
Thank you for the detailed report. Apparently, the NextJs image example is missing the `onClick` handler.

Please find necessary changes in the following sandbox - https://codesandbox.io/p/devbox/yet-another-react-lightbox-234-c3pcjw?file=%2Fcomponents%2FNextJsImage.tsx

I'll also go ahead and update the examples in the documentation.

**Comment by igordanchenko** [comment]
Up-to-date example is now live - https://yet-another-react-lightbox.com/examples/nextjs

**Comment by ygor-infotera** [comment]
Thank you very much for the quick reply and updated code!!
