### ISSUE TITLE
Video plugin doesn't work on Safari 17.3.1

### ISSUE THREAD

**Issue by piowyg** [igordanchenko/yet-another-react-lightbox#245]
### Describe the bug

In every browser videos display in right way. 
But on Safari (desktop and mobile) it doesn't works.
Even on your [stackblitz](https://stackblitz.com/edit/yet-another-react-lightbox-examples?file=src%2Fexamples%2FVideoPlugin.tsx&initialPath=/plugins/video) video is not displaying 

### Expected behavior

Showing up video in lightbox

### How to reproduce

Check it out on this [stackblitz](https://stackblitz.com/edit/yet-another-react-lightbox-examples?file=src%2Fexamples%2FVideoPlugin.tsx&initialPath=/plugins/video)

**Comment by igordanchenko** [comment]
StackBlitz demos may not work properly in Safari, and this is an expected behavior at the moment.

https://developer.stackblitz.com/platform/webcontainers/browser-support#safari

You can download StackBlitz demos and run them locally to test the Video plugin in Safari.
