### ISSUE TITLE
Problem with "scrollToZoom" option and Inline plugin

### ISSUE THREAD

**Issue by igordanchenko** [igordanchenko/yet-another-react-lightbox#248]
### Discussed in https://github.com/igordanchenko/yet-another-react-lightbox/discussions/247

<div type='discussions-op-text'>

<sup>Originally posted by **edubeckha** March  9, 2024</sup>
Hi guys,

I'm trying the "scrollToZoom" option on my Lightbox component, but when I use it the entire page keeps getting scrolled as well. Is there a way to disable this behavior?

Thank you in advance!</div>

<div type='discussions-op-text'>

<sup>Originally posted by **edubeckha** March  10, 2024</sup>
Hi Igor,

I created a minimal example of what I'm trying to achieve here: https://stackblitz.com/edit/yet-another-react-lightbox-sandbox-52ybef?file=src%2Fmain.tsx

It's easier to notice this behaviour if you open it in a new window. When I have other components (like a bunch of text for example) before and after the image gallery and try to apply zoom to the image only using the mouse scroll, the entire page scrolls up or down.

It seems that maybe there is a problem with event propagation coming from the gallery to the window, but I'm not sure how to stop it from happenning.

Thank you again!</div>

<div type='discussions-op-text'>

<sup>Originally posted by **igordanchenko** March  10, 2024</sup>
Thank you for the repro, this is very helpful. Indeed, propagation of wheel events needs to be cancelled in this case. I'll address this in the next patch release.</div>

**Comment by timhc22** [comment]
this seems to be an issue again for me in 3.18.0. i know this is a different package, but is this related at all?
https://github.com/frontend-collective/react-image-lightbox/issues/60

**Comment by igordanchenko** [comment]
@timhc22  I do not see how it may be related, as that ticket describes an entirely different issue. Please feel free to open a separate ticket and provide a [minimal repro](https://stackblitz.com/edit/yet-another-react-lightbox-sandbox?file=src%2FApp.tsx).
