### ISSUE TITLE
Inline plugin - unable to scroll the page with mouse wheel in desktop Safari

### ISSUE THREAD

**Issue by igordanchenko** [igordanchenko/yet-another-react-lightbox#256]
### Discussed in https://github.com/igordanchenko/yet-another-react-lightbox/discussions/255

<div type='discussions-op-text'>

<sup>Originally posted by **Andr3wTayl0r** March 29, 2024</sup>
When I hover over an inline Lightbox in desktop Safari (17.3.1) I am unable to scroll the page down - but move the pointer to somewhere other than the Lightbox and scrolling works.  This looks like a Safari issue as Chrome does not have this problem.

Try doing that here: [https://yet-another-react-lightbox.com/plugins/inline](https://yet-another-react-lightbox.com/plugins/inline)

Any ideas as to a fix or work-around?

Thanks</div>

**Comment by kittitadX8** [comment]
**yet-another-react-lightbox v 3.17.2**
- **Nextjs 14.0.4** Cant scroll the page down on **Mac Safari**
- **React Vite 18.2.0** Can be used

**Comment by igordanchenko** [comment]
@kittitadX8 unable to reproduce
