### ISSUE TITLE
Position start or end Responsive Layout Issue

### ISSUE THREAD

**Issue by faizananwerali** [igordanchenko/yet-another-react-lightbox#258]
### Describe the bug

If you set position start or end for desktop layout, then in mobile layout is not looking good.

### Expected behavior

Option to set position for responsive layouts.

### How to reproduce

```ts
const [position, setPosition] = React.useState<"top" | "bottom" | "start" | "end">("start");

// use it in thumbnails config
        thumbnails={{
          position,
        }}
```

### Screenshots / Logs

<img width="500" alt="Screenshot 2024-04-05 at 10 24 25 PM" src="https://github.com/igordanchenko/yet-another-react-lightbox/assets/12691366/b763fb1c-7de7-4fbf-a967-be3d8174c58c">

### Additional context

I am not sure if my solution is correct, but this is what I have done for now to resolve the issue.

```ts
import { useMediaQuery } from "react-responsive";
// ... rest of the imports

export default function CustomComponent() {
  const isMobile = useMediaQuery({ query: `(max-width: 760px)` });
  
  const [position, setPosition] = React.useState<"top" | "bottom" | "start" | "end">("start");
  
  useEffect(() => {
    setPosition(isMobile ? "bottom" : "start");
  }, [isMobile]);

        //Use it in the thumbnails config
        thumbnails={{
          position,
        }}
}

**Comment by igordanchenko** [comment]
You are using the right approach. 

I'm afraid I do not have any immediate plans to implement responsive parameters for the following reasons:
- the use case is not common
- it's not practical to implement responsive support for all available props
- it's not even feasible for props that accept functions as their values

As a side note, you can simplify your implementation by eliminating the state variable and React effect:

```jsx
const isMobile = useMediaQuery({ query: `(max-width: 760px)` });

// ...

thumbnails={{ position: isMobile ? "bottom" : "start" }}
```

**Comment by faizananwerali** [comment]
Good catch, I forgot. I should ditch `useEffect` state in this case.

Thanks for the help.
