### ISSUE TITLE
Favorite button

### ISSUE THREAD

**Issue by adrien3d** [igordanchenko/yet-another-react-lightbox#264]
### Is your feature request related to a problem? Please describe.

I am trying to build a photo gallery, and to have a favorite in order to be able to establish list of pictures the user like.

### Describe the solution you'd like

A button (like the download one), that appends to a list of the pictures the user likes.

### Describe alternatives you've considered

Using `react-grid-gallery` with `yet-another-react-lightbox`, but I opened an issue because I cannot make image selection and gallery working concurrently: [github issue](https://github.com/benhowell/react-grid-gallery/issues/338)

**Comment by igordanchenko** [comment]
This use case doesn't sound like a good candidate for a library feature or a dedicated plugin, as the application-level implementation of this feature is pretty trivial. 

The documentation includes several draft implementations of custom buttons. 

https://yet-another-react-lightbox.com/customization#AddingToolbarButtons
https://yet-another-react-lightbox.com/advanced#ToolbarButtons

Please feel free to open a discussion if you encounter any implementation issues.
