### ISSUE TITLE
Add props to customize (translate) aria-labels of buttons

### ISSUE THREAD

**Issue by branislav-brincko** [igordanchenko/yet-another-react-lightbox#281]
### Is your feature request related to a problem? Please describe.

For the lightbox to be accesible we need to translate aria-labels of prev, next and close buttons to different languages. 

### Describe the solution you'd like

Add "translations" prop to the lightbox. 

### Describe alternatives you've considered

For now I am doing this: 

![image](https://github.com/igordanchenko/yet-another-react-lightbox/assets/118365024/cf7fd5fe-a303-47c9-82d7-ee654190adc7)

Which works, but is kind of verbose when only reason for it is changing aria-labels.

**Comment by igordanchenko** [comment]
It sounds like you are looking for the `labels` prop.

```jsx
labels={{
  Next: "Next slide",
  Previous: "Previous slide",
  Close: "Close the lightbox",
}}
```

https://yet-another-react-lightbox.com/documentation#Lightbox
