### ISSUE TITLE
ReferenceError: overlay is not defined

### ISSUE THREAD

**Issue by sarowarhosen03** [igordanchenko/yet-another-react-lightbox#294]
### Describe the bug

`import { Lightbox } from "yet-another-react-lightbox";
import "yet-another-react-lightbox/styles.css";
const LightBox = ({ open, onController, images, ...rest }) => {
  return (
    <>
      <Lightbox
    
        open={open}
        close={() => onController(false)}
        slides={images}
        {...rest}
      />
    </>
  );
};

export default LightBox;
`
whats wrong with this code

### Expected behavior

in nextjs@14  the error apear sometimes , the error shouldnt apear

### How to reproduce

.

### Screenshots / Logs

![Screenshot from 2024-07-12 14-47-36](https://github.com/user-attachments/assets/5f05dfe4-7ede-4b98-b48d-a958047ce5a2)

### Additional context

.

**Comment by igordanchenko** [comment]
It doesn't sound like a library issue. I'm afraid I cannot provide any meaningful advice without a repro.
