### ISSUE TITLE
VoiceOver announces offscreen slides

### ISSUE THREAD

**Issue by ss81** [igordanchenko/yet-another-react-lightbox#297]
### Describe the bug

We have gallery of photos and each photo has description. When we open any photo with Lightbox, VoiceOver starts reading text of all photos instead of reading only text of active slide.

### Expected behavior

VoiceOver should read only text of active slide.

### How to reproduce

- Use recent version of package with Captions plugin.
- In our case, we have list of photos and show photos description with counter in Captions.
- Enable VoiceOver and click on any gallery image to activate Lightbox.
- VoiceOver starts reading captions of all images in gallery.

**Comment by ss81** [comment]
Possible solution which solved issue for me is to update `CarouselSlide` function in `src/modules/Carousel.tsx` and add "aria-hidden" property to slide div:
```
    return React.createElement(
        "div",
        {
            ref: containerRef,
            className: clsx(
                cssClass(cssSlidePrefix()),
                offset === 0 && cssClass(cssSlidePrefix("current")),
                cssClass(CLASS_FLEX_CENTER)
            ),
            "aria-hidden": offset !== 0,
            onClick: handleBackdropClick,
            style: style
        },
        renderSlide()
    );
```

**Comment by igordanchenko** [comment]
Thank you for bringing this up! Indeed, setting `aria-hidden` on offscreen slides sounds like the right solution.

I started reading W3C recommendatios on [carousel patterns](https://www.w3.org/WAI/ARIA/apg/patterns/carousel/) and they recommend setting `role="group"` and `aria-roledescription="slide"` on individual slides. However, when I do that, VoiceOver no longer reads slide title and description (even if I assign them `role="heading"` and `aria-level`). Do you have any thoughts on what should the right approach here?

Also, `role="presentation"` on the lightbox itself has been bothering me for a while. It seems to me`role="dialog"` and `aria-modal="true"` should be more appropriate here.

**Comment by ss81** [comment]
Unfortunately I don't have enough experience in accessibility, so I'm not sure I can help with your question :(

Would you like me to provide PR with suggested changes or you prefer to make this update yourself?

**Comment by igordanchenko** [comment]
> Unfortunately I don't have enough experience in accessibility, so I'm not sure I can help with your question :(

Fair enough. I'll hold off making the other changes for now.

> Would you like me to provide PR with suggested changes or you prefer to make this update yourself?

No worries. I'll go ahead and publish the fix shortly.
