### ISSUE TITLE
Problem with defining plugin array

### ISSUE THREAD

**Issue by anton12042001** [igordanchenko/yet-another-react-lightbox#299]
### Describe the bug

Plugins for Lightbox have to be imported via this path
import Counter from 'yet-another-react-lightbox/dist/plugins/counter'
import Zoom from 'yet-another-react-lightbox/dist/plugins/zoom'
import Fullscreen from 'yet-another-react-lightbox/dist/plugins/fullscreen'

But if you import these plugins through the dist directory, then when defining an array of plugins and passing it to Lightbox, I get into a situation where the types are swearing.

If you change the import of plugins and specify without /dist as indicated in the documentation, then the type error disappears, but the modules are not found

Even in your sandbox, presented in the documentation, plugins are taken from the dist directory

### Expected behavior

Plugins should be taken from a directory without dist

### How to reproduce

import Counter from 'yet-another-react-lightbox/dist/plugins/counter'
import Zoom from 'yet-another-react-lightbox/dist/plugins/zoom'
import Fullscreen from 'yet-another-react-lightbox/dist/plugins/fullscreen'

### Screenshots / Logs

![image](https://github.com/user-attachments/assets/8204c7e2-e81a-42a7-859c-5c80479c1f2e)
![image](https://github.com/user-attachments/assets/eec2d30b-8c0c-4954-a789-d08d7ab7b33c)
![image](https://github.com/user-attachments/assets/61c6cf13-eb69-4b69-a928-2794ebdc2bcc)

**Comment by igordanchenko** [comment]
> Но если импортировать эти плагины через директорию dist, то при определении массива плагинов и передача его в Lightbox попадаю в ситуацию, когда ругаются типы.
Если поменять импорт плагинов и указывать без /dist как указано в документации, то ошибка типов пропадает, но модули не найдены

You forgot to mention your bundler / build toolchain. Are you by any chance using an antiquated version of `react-scripts`? If that's the case, then you can find some workarounds by searching the Issues and Discussions using the "CRA" keyword. But generally speaking, this library is not compatible with outdated CRA versions.

```js
import Counter from 'yet-another-react-lightbox/dist/plugins/counter'
import Zoom from 'yet-another-react-lightbox/dist/plugins/zoom'
import Fullscreen from 'yet-another-react-lightbox/dist/plugins/fullscreen'
```

The above import paths are incorrect. All plugins must be imported without the "dist" part in the import path. 

Here are the correct imports:

```js
import Counter from 'yet-another-react-lightbox/plugins/counter'
import Zoom from 'yet-another-react-lightbox/plugins/zoom'
import Fullscreen from 'yet-another-react-lightbox/plugins/fullscreen'
```

**Comment by anton12042001** [comment]
Thank you, it helped
