### ISSUE TITLE
Unexpected appearance padding for position fixed

### ISSUE THREAD

**Issue by anton12042001** [igordanchenko/yet-another-react-lightbox#301]
### Describe the bug

When opening a lightbox, elements that contain the position: fixed
property are inexplicably given padding-right, which is redundant and
can break the app.
        Which is what happened in my case.
        
I understand that the behavior should be tied to the body so that nothing jumps when the scroll is removed. But padding-right is added to other elements too.

### Expected behavior

Fixed position elements do not have right padding applied.

### How to reproduce

I provide you with a sandbox with different cases that arise when such a problem occurs.

https://stackblitz.com/edit/vitejs-vite-qefy88?file=src%2FApp.tsx

**Comment by igordanchenko** [comment]
This is a documented feature and it's working as intended. Here is how you can learn more about it.

1) Open the documentation https://yet-another-react-lightbox.com/documentation
2) Open the browser search box (Command + F / Ctrl + F depending on your OS)
3) Enter "fixed" keyword and search the documentation page

The documentation also provides specific details on how to disable this feature if it's causing undesired side-effects.

**Comment by igordanchenko** [comment]
Another possible solution is to separate fixed positioning and presentation styles by adding a `<div>` wrapper that just defines the position without any presentation styles.

https://stackblitz.com/edit/yet-another-react-lightbox-301?file=src%2FApp.tsx,src%2FApp.css
