### ISSUE TITLE
Video slides get keyboard focus (via tab) even when not the active slide or the first slide

### ISSUE THREAD

**Issue by theo-staizen** [igordanchenko/yet-another-react-lightbox#304]
### Describe the bug

Given I have a carousel with a video slide and some images, even if the video is not active, it will still get focus when using tab key

### Expected behavior

Video should only be tab accessible when it is the active slide.

### How to reproduce

1. Go to video plugin demo page: https://yet-another-react-lightbox.com/plugins/video
2. Open the lightbox
3. Click on next button to move to 2nd or 3rd slide
4. Press Tab key 
5. Press enter/space. The video will start playing

### Additional context

It's possible for a keyboard user to get "trapped" in the hidden video element and not being able to use left/right arrows to move slides, since the video element has multiple tab stops (pause/play button, volume control, etc) and some of them can intercept left/right arrows.

**Comment by igordanchenko** [comment]
Thank you for reporting this accessibility issue.
