### ISSUE TITLE
Carousel navigation by mouse button stops working

### ISSUE THREAD

**Issue by razzeee** [igordanchenko/yet-another-react-lightbox#305]
### Describe the bug

Goto https://yet-another-react-lightbox.com/examples/carousel
1. Use your mouse wheel horizontal scroll click button
2. It navigates to the next slide
3. Try it again
4. Nothing happens

### Expected behavior

It should navigate to the next slide

### How to reproduce

See above

**Comment by igordanchenko** [comment]
Hi there. Will you be able to debug this issue locally and see what exactly is causing this behavior? I'm afraid I do not have the necessary hardware to reproduce and troubleshoot this on my end.

**Comment by razzeee** [comment]
I can try to have a look, it feels like some event handler gets removed

**Comment by igordanchenko** [comment]
Wheel events are handled here - https://github.com/igordanchenko/yet-another-react-lightbox/blob/main/src/modules/Controller/useWheelSwipe.ts

**Comment by razzeee** [comment]
We seem to get trapped in https://github.com/igordanchenko/yet-another-react-lightbox/blob/main/src/modules/Controller/useWheelSwipe.ts#L74-L77

**Comment by igordanchenko** [comment]
Do you mind capturing sample events with `console.log` and posting here?

**Comment by razzeee** [comment]
```
Math.abs(event.deltaX) <= 1.2 * Math.abs(wheelResidualMomentum.current)
```

ends up with 80 to 100 (slightly rounded)

**Comment by igordanchenko** [comment]
Can you capture a sample with the following logger, pls?

```js
console.log(
  event.timeStamp,
  event.type,
  event.deltaX,
  event.deltaY,
  event.deltaMode,
  event.altKey,
  event.ctrlKey,
  event.shiftKey,
  event.metaKey,
);
```

**Comment by razzeee** [comment]
I changed the log to:

```
     console.log(
        event.timeStamp,
        event.type,
        event.deltaX,
        event.deltaY,
        event.deltaMode,
        event.altKey,
        event.ctrlKey,
        event.shiftKey,
        event.metaKey,
        wheelResidualMomentum.current,
      );
```

First time, when it works:
```
4996 wheel 84 0 0 false false false false 0
```

Then I get 8 of these, just with a slightly different timestamp

```
6650 wheel 84 0 0 false false false false 84
```

**Comment by igordanchenko** [comment]
Does your mouse wheel always produce wheel events with `deltaX: 84`? That's quite unusual...

**Comment by razzeee** [comment]
Might be normal for a razer basilisk v3, I can play around with the modifier buttons later tonight. For what it's worth, it works with the embla carousel mouse plugin.

**Comment by razzeee** [comment]
tried at work with a logitech mouse (https://www.logitech.com/en-us/products/mice/m500s-corded-mouse.910-005783.html)

got these result and couldn't even page to the next side

```
48385 wheel 60 0 0 false false false false 0
```

**Comment by razzeee** [comment]
So the same mouse from the initial testing on the computer that I did the last tests with also returns `60`. I can get it to change by zooming in/out. All other mouse buttons don't seem to change stuff.

**Comment by igordanchenko** [comment]
Can you see how many events a single click produces? Is it a single event or a series of events?

What happens when you press and hold the button? Does it emit subsequent events with identical `deltaX` values? At what intervals?

**Comment by razzeee** [comment]
When it works it's one event.

When it doesn't work, it's about 8 events per second/click. Holding it will just spam them and they are the same, other then the timestamp. Interval seems to be 20ms apart each.

**Comment by igordanchenko** [comment]
Thank you for capturing these data points. I'll go ahead and publish a fix that I believe should address this issue.

**Comment by razzeee** [comment]
Thank you, way better then before. But it gets unresponsive, if you start to click faster. Then it will just not react to presses into a certain direction.

**Comment by igordanchenko** [comment]
> Thank you, way better then before. 

Thank you for confirming it resolved the issue.

> But it gets unresponsive, if you start to click faster. Then it will just not react to presses into a certain direction.

You can consider it a limitation of the current implementation. It's the same unsupported behavior as if you were to press and hold the horizontal scroll button.
