### ISSUE TITLE
Importing css is not working on GatsbyJS  in production build

### ISSUE THREAD

**Issue by hotyes** [igordanchenko/yet-another-react-lightbox#307]
### Describe the bug

Importing css from npm package for a gatsbyjs project works in develop, but not on serve

Many simliar issues report in here https://github.com/gatsbyjs/gatsby/issues/19446

Solution: 

https://github.com/gatsbyjs/gatsby/issues/19446#issuecomment-553019807

`CSS has a side effect: "adding CSS to the DOM". You can't mark it as side-effect-free. ` (https://github.com/webpack/webpack/issues/6741#issuecomment-372720641)

### Expected behavior

It should be styled in the production build.

### How to reproduce

1, Create a gatsbyjs project from a simplest starter 
2, Install `yet-another-react-lightbox` package
3, `gatsby build`
4, serve in any web server

**Comment by igordanchenko** [comment]
Unable to reproduce. Please provide a minimal repro.

**Comment by igordanchenko** [comment]
Not reproduced with the following minimal test.

```shell
npm init gatsby
```

```
What would you like to call your site?
✔ · gatsby-test
What would you like to name the folder where your site will be created?
✔ Temp/ gatsby-test
✔ Will you be using JavaScript or TypeScript?
· TypeScript
✔ Will you be using a CMS?
· No (or I'll add it later)
✔ Would you like to install a styling system?
· No (or I'll add it later)
✔ Would you like to install additional features with other plugins?No items were selected
```

```shell
cd gatsby-test
npm i yet-another-react-lightbox
```

```tsx
// index.tsx
import Lightbox from  "yet-another-react-lightbox";
import "yet-another-react-lightbox/styles.css";

// ...

<Lightbox open />

// ...
```

```shell
npm run build
npm run serve
```

FWIW, this library already declares `*.css` files as side effects.
