### ISSUE TITLE
Extra padding

### ISSUE THREAD

**Issue by AHTOHO4** [igordanchenko/yet-another-react-lightbox#321]
### Describe the bug

Hi.
I have encountered the following problem:
When I open the likebox, I see that the body tag is assigned the class yarl__no_scroll, and so is padding-right. But the problem is that when I open devtools, I see that the padding is very large. The more devtools is opened (i.e. technically, the smaller the window is in relation to the entire screen), the larger the padding-right is assigned

![image](https://github.com/user-attachments/assets/c725295c-324c-46bc-bb4c-3f65d082cd80)
![image](https://github.com/user-attachments/assets/34712c0c-9ea0-40f1-989d-63a4d5bc0bb8)

Unfortunately, I was unable to prepare an example and reproduce the problem in the sandbox. I assume that this is due to the fact that an iframe is used there.

If I first open the lightbox, and then devtools, I see an adequate padding-right: 15px
![image](https://github.com/user-attachments/assets/53e0e34c-37e5-4606-a5fd-45d5a25ae896)

Questions:
1) What could possibly be the problem and how can I try to fix it?
2) Maybe I should somehow remove padding-right, leaving the classes. Will this be the right solution or is it more like a crutch?

### Expected behavior

Normalize padding

### How to reproduce

Couldn't reproduce in sandbox, presumably because it uses iframe

**Comment by igordanchenko** [comment]
Duplicate #320
