### ISSUE TITLE
"click" Lifecycle callback does not work with custom render

### ISSUE THREAD

**Issue by sagan** [igordanchenko/yet-another-react-lightbox#322]
### Describe the bug

I want to hide the controls when tapping / clicking the image. After a simple search I found #78, which is exactly what I want.

However, I found that the suggested solution does NOT work with a custom slide render, the click callback just won't be triggered.

### Expected behavior

The click lifecycle callback should work with custom render

### How to reproduce

See below.

### Additional context

I workaround this problem by passing onClick directly to custom render using closure, it works, but is not elegant and may have performance problem.

```tsx
import React, { useCallback, useMemo } from "react";
import Lightbox, { RenderSlideProps } from "yet-another-react-lightbox";

interface RenderSlidePropsWithCallbacks extends RenderSlideProps {
  onClick?: () => void;
}

function SlideRender({ slide, rect, onClick }: RenderSlidePropsWithCallbacks) {
  return <div onClick={onClick}>
    ...
  </div>;
}

function App({ }) {
  const [hideLightboxControls, setHideLightboxControls] = React.useState(false);

  const toggleLightboxControls = useCallback(() => setHideLightboxControls((state) => !state), []);

  const SlideRenderWrap = useMemo<React.FC<RenderSlidePropsWithCallbacks>>(() => {
    return function ({ slide, ...others }) {
      if (slide.type == "image") {
        return undefined;
      }
      return <SlideRender onClick={toggleLightboxControls} slide={slide} {...others}></SlideRender>;
    };
  }, []);

  <Lightbox
    on={{ click: toggleLightboxControls }}
    className={hideLightboxControls ? "yarl__hide-controls" : undefined}
    render={{ slide: SlideRenderWrap }}
  // ...
  />
}


```

**Comment by igordanchenko** [comment]
Hi there! Thank you for bringing this up. It's not a bug per se, but rather a quirk of the current implementation. When implementing your custom slides, you are in control of defining which parts of a slide should register as "click" event as opposed to user interaction with let's say form controls or video player controls. To avoid using closures in this case, you can access the `on.click` callback from your custom slide component with the `useLightboxProps` hook. You can find a specific example in the Next.js image implementation - https://yet-another-react-lightbox.com/examples/nextjs#next/image

Please let me know if you have any further questions.

**Comment by sagan** [comment]
Thank you for the reply. It solved my problem.
