### ISSUE TITLE
Want to play Youtube video for the slides.

### ISSUE THREAD

**Issue by Satosh-J** [igordanchenko/yet-another-react-lightbox#49]
### Is your feature request related to a problem? Please describe.

I have several youtube video links to be displayed in the light box.
How should I do that?

### Describe the solution you'd like

I want the slides props to approve youtube links.

**Comment by igordanchenko** [comment]
Here is a live demo - https://codesandbox.io/s/yet-another-react-lightbox-16-bwx8nc

**Comment by Satosh-J** [comment]
Thank you for your reply.
But, custom props is not allowed for the Typescript project.
What should I do in this case?

**Comment by igordanchenko** [comment]
I believe this is covered in the [documentation](https://yet-another-react-lightbox.com/examples/custom-slides), and there is a live demo in the [How to create CustomSlide in TypeScript?](https://github.com/igordanchenko/yet-another-react-lightbox/discussions/47) discussion.

**Comment by returnvoid** [comment]
Great componente. I'm trying to have images and YouTube videos in the Lightbox, is it possible? 
Also there is something I don't quite understand about the render method. I have in the slides array items with type="youtube". In the render method I'm doing a conditional evaluation like:

`render={{
    slide: slide => {
      slide.type === 'youtube' ? (
        <iframe
          key={slide.key}
          width="500"
          height="320"
          src={slide.src}
          title="My Video"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
          allowFullScreen
        />
      ) : null;
    },
  }}`

In the examples I see using the value null if it's other than type="YouTube". I did that in an array with regular images slides plus some videos. But I only see the regular images rendered in the Lightbox, the iframe comes empty. Not quite sure about that null value then

thanks

**Comment by igordanchenko** [comment]
The example you grabbed this code from was based on YARL v2, but I'm assuming you are now using YARL v3 in your project. The parameters of the `slide` render function [have changed in v3](https://github.com/igordanchenko/yet-another-react-lightbox/issues/90), so you need to destructure `slide` function props:

```jsx
render={{
  slide: ({ slide: { type, src, width, height, title }, rect }) =>
    type === "youtube" ? (
      <iframe
        width={Math.min(width, rect.width, (width * rect.height) / height)}
        height={Math.min(height, rect.height, (height * rect.width) / width)}
        src={src}
        title={title}
        frameBorder="0"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
        allowFullScreen
      ></iframe>
    ) : null
}}
```

I've updated the [example](https://codesandbox.io/s/yet-another-react-lightbox-16-bwx8nc?file=/src/App.js) for v3.

**Comment by returnvoid** [comment]
> The example you grabbed this code from was based on YARL v2, but I'm assuming you are now using YARL v3 in your project. The parameters of the `slide` render function [have changed in v3](https://github.com/igordanchenko/yet-another-react-lightbox/issues/90), so you need to destructure `slide` function props:
> 
> ```js
> render={{
>   slide: ({ slide: { type, src, width, height, title }, rect }) =>
>     type === "youtube" ? (
>       <iframe
>         width={Math.min(width, rect.width, (width * rect.height) / height)}
>         height={Math.min(height, rect.height, (height * rect.width) / width)}
>         src={src}
>         title={title}
>         frameBorder="0"
>         allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
>         allowFullScreen
>       ></iframe>
>     ) : null
> }}
> ```
> 
> I've updated the [example](https://codesandbox.io/s/yet-another-react-lightbox-16-bwx8nc?file=/src/App.js) for v3.

amazing, working! thanks
