### ISSUE TITLE
Video plugin not updating on delete

### ISSUE THREAD

**Issue by g3rg** [igordanchenko/yet-another-react-lightbox#50]
### Describe the bug

As per #38 for the Zoom plugin, the video plugin does not update the current video slide correctly if the current slide is deleted and the next slide is also a video slide. Works fine if next slide is just an image though.

### Expected behavior

When a video is deleted, and the next slide is also a video, it should update to show the next video.

### How to reproduce

Added a delete function that results in an update of the underlying image collection to no longer include the current video. If the next slide is also a video, it is not updated correctly, though does seem to update width/height, just not the source.

**Comment by igordanchenko** [comment]
Thank you for this bug report. Can you please confirm v2.2.5 resolves your issue?

**Comment by g3rg** [comment]
@igordanchenko I've just updated and tested, and works perfectly, thanks for the quick response and fix!
