### ISSUE TITLE
Click overlay to close the lightbox

### ISSUE THREAD

**Issue by tinwritescode** [igordanchenko/yet-another-react-lightbox#53]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

I'm glad you brought this up! It would be a good idea to allow users to close the lightbox by clicking on the overlay. This would provide a convenient and intuitive way for users to dismiss the lightbox and return to the underlying page content.

Here's how the feature could work: When the lightbox is displayed, an overlay is added to the page. If the user clicks on the overlay, the lightbox is closed and the overlay is removed from the page.

I hope this helps clarify the feature request. Let me know if you have any further questions or suggestions.

Best regards, Tin Nguyen

**Comment by igordanchenko** [comment]
Thank you for submitting this feature request. Based on your description, it sounds like `controller.closeOnBackdropClick` is the option you are looking for. Can you please confirm this is the experience you had in mind?

```jsx
<Lightbox
  controller={{ closeOnBackdropClick: true }}
  // ...
/>
```

Live demo - https://codesandbox.io/s/yet-another-react-lightbox-53-xmcwf4

**Comment by tinwritescode** [comment]
Sound like the option I was looking for. Thank you for your help!!!
