### ISSUE TITLE
Top of image clipped when rendering slideFooter and content exceeds vertical bounds

### ISSUE THREAD

**Issue by rolanday** [igordanchenko/yet-another-react-lightbox#55]
### Describe the bug

With no customer slideFooter rendered, img scales to fit when resizing window. When adding custom footer using render.slideFooter option, the top of the image clips proportional to the height of customer footer content. See screen shots attached, one with and the one without customer footer.

### Expected behavior

Image resizing behavior using custom rendered footer is the same as using the default footer.

### How to reproduce

1. Add customer footer:
```
                              render={{
                                slideFooter: (slide) => {
                                  return <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec rhoncus pretium iaculis. Vivamus mollis felis condimentum, dignissim tellus non, accumsan nunc. Nunc viverra id metus ac sollicitudin. Sed ipsum ipsum, ullamcorper ut posuere et, placerat vel ligula. Aliquam erat volutpat. Mauris consequat diam in velit eleifend ullamcorper. Mauris iaculis consectetur ipsum vitae interdum. In hac habitasse platea dictumst. Etiam consectetur nisi dolor, et varius dolor lacinia ut. Suspendisse convallis vestibulum nisi a aliquam. Nullam ultricies lobortis volutpat. Maecenas non vestibulum felis. Vivamus varius, nibh sit amet porta convallis, turpis urna congue elit, non posuere massa ligula in dolor. Phasellus vestibulum erat ac odio rhoncus accumsan. Mauris velit dui, tempus et tellus sed, rhoncus tempus ligula.</div>;
                                },
                              }}
```
2. Resize main window and observe top of image being clipped.

## No custom footer
<img width="505" alt="Screen Shot 2023-01-04 at 2 40 33 PM" src="https://user-images.githubusercontent.com/3402123/210664018-eaa09427-ebbc-448c-aba8-99df11f4d506.png">

## Custom footer
<img width="524" alt="Screen Shot 2023-01-04 at 2 39 15 PM" src="https://user-images.githubusercontent.com/3402123/210664021-ae67d969-3de0-4efd-8526-6146ef69b8e3.png">

**Comment by rolanday** [comment]
Update: If I set custom footer to clip on overflow, then I get the expected behavior. Possibly current behavior is by design? I was expecting yarl to be aware of custom footer dims and resize image accordingly, but simple enough to set CSS prop on footer.

**Comment by igordanchenko** [comment]
You are correct, YARL does not measure header and footer elements dimensions. `slideHeader` and `slideFooter` render functions were added to allow adding absolutely positioned elements to the DOM (i.e. slide title and description in the Captions plugin). Based on the above screenshots you probably want to render custom slide via `render.slide` render function. Please let me know if this addresses your use case.

**Comment by rolanday** [comment]
Hi Igor, thanks for the reply and you contribution in general. Very well thought out and super appreciated! I'll look at rendering a custom slide once I start fine-tuning. One thing missing for me (or maybe I missed it?) is an interface for advancing/setting slide after mount. I'll create feature request after double-checking or if you confirm not currently supported. Again, thank you.

**Comment by igordanchenko** [comment]
Hi Roland,

> One thing missing for me (or maybe I missed it?) is an interface for advancing/setting slide after mount.

The `index` prop determines the initial slide index when the lightbox opens. Once mounted, the lightbox maintains its own state internally. You can advance to the next / previous slide programmatically via `useEvents().publish` hook (it's not covered in the public API documentation, but it's part of the lightbox core API which is pretty stable at this point). I put together a small demo to illustrate this approach.

https://codesandbox.io/s/yet-another-react-lightbox-55-ox9svu?file=/src/App.js:475-486

Does this answer your question?

**Comment by rolanday** [comment]
Yes, it certainly does.  Perfect. Thank you so much!

**Comment by igordanchenko** [comment]
Thanks for confirming. I'll go ahead and close this ticket then.
