### ISSUE TITLE
Captions plugin - support HTML in description

### ISSUE THREAD

**Issue by Adstokoe19** [igordanchenko/yet-another-react-lightbox#56]
### Is your feature request related to a problem? Please describe.

Currently the `slides` prop only accepts a slide description as plain text.

### Describe the solution you'd like

Would it be possible to allow for HTML in the description? I would like to use emojis...etc in the caption. Thanks.

**Comment by igordanchenko** [comment]
Captions plugin accepts `title` and `description` props as `React.ReactNode` type, so you can pass jsx markup as slide title and description.

```jsx
<Lightbox
    slides={slides.map((slide) => ({
        ...slide,
        title: <><span>Title</span>&nbsp;&#129409;</>,
        description: <><h3>Description</h3>&#129409;</>,
    }))}
    plugins={[Captions]}
    // ...
/>
```

However, parsing HTML markup from the text description is outside this library's scope. But the good news is that there is plenty of 3rd-party libraries you can use depending on the data format you wish to support (HTML, markdown, etc.)
