### ISSUE TITLE
Dragging Slide glitchy on Firefox (v2.2.5)

### ISSUE THREAD

**Issue by xAlban** [igordanchenko/yet-another-react-lightbox#58]
### Describe the bug

When you drag the slide of the lightbox with the mouse on Firefox, the slide doesn't follow the mouse and glitch in the middle. On Chrome it follows the mouse but sometimes stays stuck in a 'in-between' state.

### Expected behavior

The drag of the slide should be smooth and follow the mouse. Or there should be a prop to deactivate the slide on desktop.

### How to reproduce

Open any official demo in Firefox and Drag a Slide with the mouse.

**Comment by igordanchenko** [comment]
Thank you for submitting this bug report. I'll look into Firefox glitch. However, I haven't seen the behavior you describe in Chrome. Would you mind posting a screen recording or repro steps?

**Comment by igordanchenko** [comment]
I'll go ahead and release a fix for Firefox glitch. Please feel free to open a separate ticket for "stuck in a 'in-between' state" issue in Chrome since these are two separate issues.

**Comment by igordanchenko** [comment]
Fixed in 2.2.6

**Comment by xAlban** [comment]
Thank you for the very quick fix Igor !
