### ISSUE TITLE
Video coved when the thumbnails plugin is enabled

### ISSUE THREAD

**Issue by rigon** [igordanchenko/yet-another-react-lightbox#62]
### Describe the bug

The video is covered by thumbnails, not showing the whole video frame, specially the area with the controls of the video. The video is not fitted on the screen from the sides as well.

### Expected behavior

Show the video entirely on the screen.

### How to reproduce

Enable the video and the thumbnails plugins. Then load a slide with a video.

### Additional context

The option `imageFit` from the Carousel is not respected, setting to `contain` or `cover` does not produce any result.

**Comment by igordanchenko** [comment]
Please provide a code sandbox demonstrating this issue.

**Comment by rigon** [comment]
I see my mistake. I wasn't specifying the dimensions (width and height). With that, it works just fine.
Anyhow, a bit annoying having to specify the dimensions. Could this be improved?

**Comment by igordanchenko** [comment]
If you inspect the DOM, you can see that the Video plugin renders the `<video>` element with specified width and height attributes, even before the user initiates the video playback. So this kind of creates a chicken and egg problem. I'll be happy to improve the plugin if you can suggest a cross-browser solution that works in the most popular desktop and mobile browsers.
