### ISSUE TITLE
Module not found errors

### ISSUE THREAD

**Issue by zehawki** [igordanchenko/yet-another-react-lightbox#7]
### Describe the bug

Getting the following:

1. Module not found: Can't resolve 'yet-another-react-lightbox/styles.css'
2. Module not found: Can't resolve 'yet-another-react-lightbox/plugins/zoom' 

### Expected behavior

Should work as given in the example and CSB.

### How to reproduce

Just the basic example as given in https://github.com/igordanchenko/yet-another-react-lightbox#minimal-setup-example

**Comment by igordanchenko** [comment]
Please post a complete repro as so far it looks like you just forgot to install the package.

**Comment by zehawki** [comment]
Package is installed just fine :-) You can see in the screenshot here that its working. 

![image](https://user-images.githubusercontent.com/8095144/181269653-2462f65a-b0b2-473f-b05c-b954a46054e1.png)

For the moment, I took the contents of the styles.scss into my build. However cant get any plugin to work, and also cant import the styles.css.

Just straight forward code:

```
import Lightbox from "yet-another-react-lightbox";
// import "yet-another-react-lightbox/styles.css";
// import Zoom from "yet-another-react-lightbox/plugins/zoom";
// import Video from "yet-another-react-lightbox/plugins/video";
// import { Fullscreen } from "yet-another-react-lightbox/plugins";

const PhotoGrid = () => {
  const [open, setOpen] = useState(false);

  const slides = [
    { src: "https://placekitten.com/1500/500" },
    { src: "https://placekitten.com/4000/3000" },
    { src: "https://placekitten.com/800/1200" },
  ]

  return (
    <>
      <button type="button" onClick={() => setOpen(true)}>
        Open Lightbox
      </button>

      <Lightbox
        open={open}
        close={() => setOpen(false)}
        slides={slides}
        // plugins={[Zoom]}
        animation={{ zoom: 500 }}
        zoom={{
          maxZoomPixelRatio: 1,
          zoomInMultiplier: 2,
          doubleTapDelay: 300,
          doubleClickDelay: 500,
          doubleClickMaxStops: 2,
          keyboardMoveDistance: 50,
          wheelZoomDistanceFactor: 100, 
          pinchZoomDistanceFactor: 100,
        }}
      />

    </>
  );
};

export default PhotoGrid;
```

**Comment by igordanchenko** [comment]
What’s your node and npm/yarn version?

**Comment by zehawki** [comment]
Node = v16.14.1
Yarn = v1.22.18

**Comment by igordanchenko** [comment]
Alright. Can you provide a complete minimal repro? Not just the code snippet, but the whole minimal project reproducing the issue. The code snippet you posted works just fine - https://codesandbox.io/s/yet-another-react-lightbox-sandbox-forked-u8prpf?file=/src/App.js

**Comment by zehawki** [comment]
Yes I understand. Unfortunately there is no conceivable way for me to share something standalone that can reproduce this issue. Its a huge project and this is 1 component among more than 2000 internal and external. Maybe its something to do with how you are exporting.

**Comment by igordanchenko** [comment]
The package is using subpath exports that were added in Node 12.7.0 - https://nodejs.org/api/packages.html#subpath-exports, but that shouldn't be an issue since you are using a recent Node version. I'm not sure how to troubleshoot your issue without knowing the specifics of you project or having a minimal repro case. Can you at least tell me what kind of bundler / framework is used? (webpack, next.js, create react app, etc.)

**Comment by igordanchenko** [comment]
Oh and just out of curiosity, can you try changing imports to 

```jsx
import "yet-another-react-lightbox/dist/styles.css";
import Zoom from "yet-another-react-lightbox/dist/plugins/zoom";
```

**Comment by zehawki** [comment]
> Can you at least tell me what kind of bundler / framework is used? (webpack, next.js, create react app, etc.)

Yes of course :-) Its CRA 4.0.3. React 17.

```
import "yet-another-react-lightbox/dist/styles.css";
import Zoom from "yet-another-react-lightbox/dist/plugins/zoom";

```
Works just fine! With 1 small change: `import Zoom from "yet-another-react-lightbox/dist/plugins/Zoom";`

**Comment by igordanchenko** [comment]
I don't know what's so special about CRA 4 (maybe an old webpack version) that's causing it to completely ignore package import maps, and I can't even troubleshoot it as CRA 4 won't event install for me:

```
npx create-react-app@4.0.3 cra4-test
Need to install the following packages:
  create-react-app@4.0.3
Ok to proceed? (y) y
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.

You are running `create-react-app` 4.0.3, which is behind the latest release (5.0.1).

We no longer support global installation of Create React App.

Please remove any global installs with one of the following commands:
- npm uninstall -g create-react-app
- yarn global remove create-react-app

The latest instructions for creating a new app can be found here:
https://create-react-app.dev/docs/getting-started/
```

**Comment by igordanchenko** [comment]
As it turns out, this is a known issue in CRA 4 - https://github.com/facebook/create-react-app/issues/10892, but it didn't get any attention from CRA devs since Apr 2021. Upgrading to CRA 5 should resolve this issue.

**Comment by igordanchenko** [comment]
Webpack aliases can provide a workaround for CRA 4. Here is an example using [craco](https://www.npmjs.com/package/@craco/craco):

```js
// craco.config.js

const path = require("path");

module.exports = {
    webpack: {
        alias: {
            "yet-another-react-lightbox/styles.css": path.resolve(__dirname, 'node_modules/yet-another-react-lightbox/dist/styles.css'),
            "yet-another-react-lightbox/plugins/zoom": path.resolve(__dirname, 'node_modules/yet-another-react-lightbox/dist/plugins/Zoom'),
        }
    }
};
```

**Comment by ltt2801** [comment]
HI there, can you support nodejs version 12 at least. I found in your package.json supporting 14 and newer.
`    "engines": {
        "node": ">=14"
    },`

**Comment by igordanchenko** [comment]
> HI there, can you support nodejs version 12 at least.

I'm sorry, but I have no plans for that. This library was released a month after Node 12 became EOL. You can still install this package under Node 12 if you must continue using Node 12.

**Comment by rabbl** [comment]
I have this issue, but not in the application but in my jest-tests. 

```
    Cannot find module 'yet-another-react-lightbox/plugins' from 'src/app/modules/asset-tracking/presentation/components/Datatable/Attachments.tsx'

    Require stack:
      src/app/modules/asset-tracking/presentation/components/Datatable/Attachments.tsx
      src/app/modules/asset-tracking/presentation/components/Datatable/Attachments.test.tsx
```

I could solve this adapting the jest config ths way:

```
 moduleNameMapper: {
    'yet-another-react-lightbox/plugins': '<rootDir>/node_modules/yet-another-react-lightbox/dist/plugins',
  }
```

Do you have an idea why jest does not use the same import-logic as the application code?

**Comment by igordanchenko** [comment]
@rabbl,

> Do you have an idea why jest does not use the same import-logic as the application code?

That I don't know. My experience with jest, ts-jest, ESM, and 3rd-party ESM dependencies was bumpy, to say the least. My workaround was to exclude such 3rd-party dependencies from jest transformations.

```
"transformIgnorePatterns": [
    "node_modules/(?!yet-another-react-lightbox|module1|module2|etc)"
],
```

**Comment by lyonsun** [comment]
I have same issue with Next.js 13.5.6, node 20.9.0 and npm 10.2.1. Webpack alias solution above doesn't work in my case.

**Comment by igordanchenko** [comment]
@lyonsun please feel free to open a new ticket and provide a minimal repro.
