### ISSUE TITLE
Can't reduce slides.length safely, got TypeError: Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by stonesthatwhisper** [igordanchenko/yet-another-react-lightbox#70]
### Describe the bug

I need to dynamically change the `slides` array from a length N array to a length one array, and do this under Inline mode, where `open` is ignored. Because`open` is ignored, I cannot quit the Lightbox and open it again.

In my understanding, I cannot update `index` after YARL is open, hence when I change the `slides` from a long array to a length 1 array, it is then possible for rendering-related methods in YARL to get a slide to be undefined in  [core/utils.ts:49](https://github.com/igordanchenko/yet-another-react-lightbox/blob/main/src/core/utils.ts#L49) `isImageSlide` where `slide.type` perhaps should be `slide?.type`.

### Expected behavior

YARL should just display the only image in the length 1 `slides` array without crashing.

### How to reproduce

The following code sets `slides` to be an array kept in a React state.

To reproduce, do these:
1. Set `slides` to an array longer than 1.
2. Set `slides` to an array of length 1.
3. (optional) change/update (the only) image in `slides`.
``` 
                          <Lightbox
                              slides={slides}
                              // for inline mode, this is ignored
                              //open={this.state.projectViewerOpen && slides.length > 0}
                              //close={() => console.log('close')} 
                              carousel={{ finite: true, spacing: 0 }}
                              inline={{ style: { width: '100%', height: '86vh' } }}
                              plugins={[
                                Inline,
                                Captions,
                                Fullscreen,
                                Zoom,
                              ]}
```

### Screenshots / Logs

Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'type')

Call Stack
isImageSlide
node_modules/yet-another-react-lightbox/dist/core/utils.js (28:7)
Object.slide
node_modules/yet-another-react-lightbox/dist/plugins/zoom/Zoom.js (27:35)
renderSlide
node_modules/yet-another-react-lightbox/dist/core/modules/Carousel.js (20:0)
CarouselSlide
node_modules/yet-another-react-lightbox/dist/core/modules/Carousel.js (40:220)
renderWithHooks
node_modules/react-dom/cjs/react-dom.development.js (14985:0)

**Comment by igordanchenko** [comment]
Since you are completely replacing the `slides` array, you probably want to tear down the old lightbox and have React render a new instance. To do that, you can give lightbox a `key` prop.

```jsx
<Lightbox key={slides.map(({ src }) => src).join()} ...
```

or

```jsx
<Lightbox key={slides.length} ...
```
