### ISSUE TITLE
Zoom plugin works weirdly on small pictures

### ISSUE THREAD

**Issue by pi-kei** [igordanchenko/yet-another-react-lightbox#75]
### Describe the bug

Zoom In does not work as expected.
Zoom In button is disabled after first click and my 32px x 32px picture is almost the original size,  but `maxZoomPixelRatio` is set to 32. Browser window is expanded to fullHD screen.
If I make browser window smaller at some point I can zoom in more.

### Expected behavior

I expect my 32px x 32px picture to be zoomed at max x32 from its original size when I set `maxZoomPixelRatio` to 32 (`window.devicePixelRatio` is 1).

### How to reproduce

Use Lightbox component:
1. Set `slides` to a single picture with size 32px x 32px
2. Add `Zoom` plugin
3. Set `maxZoomPixelRatio` to 32
4. Open lightbox
5. Try to zoom in

You can try here in codesandbox project https://codesandbox.io/s/cool-currying-6jorsl?file=/src/App.tsx:861-878

### Screenshots / Logs

Initial state 
![initial](https://user-images.githubusercontent.com/3518025/220461645-a4865fb5-b386-4633-8517-eddaa6d3226b.png)

Fully-zoomed-in state (fullHD window)
![fullyzoomed](https://user-images.githubusercontent.com/3518025/220461725-789039f3-4bc3-4151-8b76-8fb7cd25a417.png)

Fully-zoomed-in state (small window)
![fullyzoomedsmall](https://user-images.githubusercontent.com/3518025/220463759-af9f2d9d-de21-4f68-8c50-70f58519aec2.png)

**Comment by igordanchenko** [comment]
Thank you for the detailed report. Indeed, the current math appears to be flawed when an image is smaller than the viewport size. I'll release a fix tomorrow.
