### ISSUE TITLE
Zoom with mouse wheel / Zoom plugin

### ISSUE THREAD

**Issue by zehawki** [igordanchenko/yet-another-react-lightbox#8]
### Describe the bug

Live demo as given in https://yet-another-react-lightbox.com/plugins/zoom does not zoom with mouse wheel

### Expected behavior

Since there is a `wheelZoomDistanceFactor` param, expectation is that mouse wheel zoom works. Is that not supported?

### How to reproduce

See live demo on https://yet-another-react-lightbox.com/plugins/zoom

**Comment by igordanchenko** [comment]
Have you tried holding the Control key down while rolling the mouse wheel?

**Comment by zehawki** [comment]
Ah, I see.

Would you pls consider removing that (or making it configurable). I can image using Control + wheel on the inline version since in that case the lightbox wouldnt know if the user wants to zoom the image or scroll the page.

But once an image has opened in a (non-inline) lightbox, then its intuitive to use the wheel to zoom.

**Comment by igordanchenko** [comment]
Image zoom feature is designed to work consistently with standard webpage zoom gestures. Why would users expect scroll up / down gesture to work as zoom in the lightbox? You wouldn't expect it on a regular webpage, would you?

**Comment by zehawki** [comment]
Because its utterly intuitive to use direct wheel to zoom on a lightbox. There is nothing to scroll up/down.

Its how it works on maps (Google etc) for instance. On all these lightboxes for instance:

1. https://fslightbox.com/react (see pro)
2. https://prc5.github.io/react-zoom-pan-pinch/?path=/story/examples-big-image--big-image
3. https://frontend-collective.github.io/react-image-lightbox/
4. .. and others

And if you see photoswipe, here's the option https://photoswipe.com/options/#wheeltozoom

**Comment by igordanchenko** [comment]
Google Maps is a good example. As to other lightboxes (with the exception of photoswipe), it looks like they just do not support the standard zoom gesture as the whole page just zooms in / out, all lightbox controls disappear and it looks utterly ugly.

<img width="933" alt="Screen Shot 2022-07-27 at 12 03 40 PM" src="https://user-images.githubusercontent.com/64441155/181295929-7ab080c8-611f-4a69-88b1-149beca1fe54.png">

<img width="932" alt="Screen Shot 2022-07-27 at 12 03 50 PM" src="https://user-images.githubusercontent.com/64441155/181295909-69b3e2ef-e031-4e7e-9d2a-6cba299ba08e.png">

I do not have a goal to match all the features / configuration options out there as it contradicts the no-bloat motto of this library.

I'll give your feature request another thought and will see if there are any conflicts with the swipe gestures. If it becomes too cumbersome to implement, then it won't be implemented.

**Comment by igordanchenko** [comment]
How would you move zoomed-in image up/down when scroll up/down triggers zoom?

**Comment by igordanchenko** [comment]
> Because its utterly intuitive to use direct wheel to zoom on a lightbox. 

Alright, I can't speak for mouse users since I haven't used one in over a decade, but as a trackpad user, I can assure you it's way more intuitive to use the standard zoom and scroll gestures (pinch-to-zoom and two-finger swipe, respectively). Any mouse gesture changes would also affect trackpad users since both input devices produce the same "onwheel" events.

> There is nothing to scroll up/down.

Yes, there is. When you zoom in, and parts of the image go offscreen, vertical/horizontal scroll gestures perform the image panning function. That's precisely how these gestures work on a regular webpage.

I very much prefer the current UX, so it will remain the default. I can go ahead and implement your request as an option. However, keep in mind that your trackpad users won't be able to pan the image with a two-finger swipe. Can you confirm that's the UX you'd like to achieve?

**Comment by zehawki** [comment]
> Yes, there is. When you zoom in, and parts of the image go offscreen, vertical/horizontal scroll gestures perform the image panning function. That's precisely how these gestures work on a regular webpage.

A mouse wheel does only vertical, not horizontal. Though I hear you - you are speaking mainly from a trackpad POV, which is closer to a mobile touch screen.

> However, keep in mind that your trackpad users won't be able to pan the image with a two-finger swipe. Can you confirm that's the UX you'd like to achieve?

Yes please. Pls see also below discussion.

---

In fact, I now realize that the default is actually a UX failure. A lightbox should be treated as a modal, and a modal should expressly disallow interaction with the underlying page. Whether its mouse or trackpad, scroll is not staying limited to the image, its scrolling the underlying page and thats quite confusing since the page will show something else when the lighbox is closed.

**Comment by igordanchenko** [comment]
> A mouse wheel does only vertical, not horizontal. 

Doesn't shift + mouse wheel do the horizontal scroll? Also it's my understanding that some devices may have an additional wheel or modifier buttons.

> In fact, I now realize that the default is actually a UX failure. A lightbox should be treated as a modal, and a modal should expressly disallow interaction with the underlying page. Whether its mouse or trackpad, scroll is not staying limited to the image, its scrolling the underlying page and thats quite confusing since the page will show something else when the lighbox is closed.

Sorry, I'm confused. Are you referring to this library? This library specifically takes extra steps to prevent document body from scrolling.
