### ISSUE TITLE
next/image and responsiveness

### ISSUE THREAD

**Issue by igordanchenko** [igordanchenko/yet-another-react-lightbox#85]
### Discussed in https://github.com/igordanchenko/yet-another-react-lightbox/discussions/84

<sup>Originally posted by **jensober** March  9, 2023</sup>

I'm using the lightbox with the next/image component as described here: https://yet-another-react-lightbox.com/examples/nextjs

I get problems when I change the size of the browser window or rotate the smartphone. Here you can see a screen capture:

![LightboxNextjsResponsive](https://user-images.githubusercontent.com/8683821/224028472-c7f87fbc-940e-49e7-98cd-561f2b5be101.gif)

Is there anything I can fix here?

**Comment by jensober** [comment]
As a workaround, I use `window.screen.availWidth` resp. `window.screen.availHeight` instead of the rect parameter to calculate the width and the height.

**Comment by igordanchenko** [comment]
Thank you for catching this nasty bug! I'll release a fix later today.
