### ISSUE TITLE
Basic implementation just doesn't work.

### ISSUE THREAD

**Issue by maxratajczak** [igordanchenko/yet-another-react-lightbox#88]
### Describe the bug

Following the documentation basic implementation with adding a slides array with a src, width and height cause the light box images to open at the end of my body tag without any background or buttons. The images appear full screen width one after another as block elements.

There is no styling or "modal" like display.

### Expected behavior

Light box should open as intended without any additional settings.

### How to reproduce

Install the package, add some images and click on an image to open lightbox.

**Comment by igordanchenko** [comment]
It sounds like you forgot to import CSS styles.
