### ISSUE TITLE
Rendering custom button next & prev onClick not working

### ISSUE THREAD

**Issue by maxratajczak** [igordanchenko/yet-another-react-lightbox#89]
### Describe the bug

When rendering a custom button, clicking the button does nothing. I'm assuming it's because an onClick isn't being passed through, but the buttonNext/buttonPrev doesn't expose anything to pass through. I have also just tried setting the onClick to set the index to the next image, but the images don't slide automatically when changing it manually.

### Expected behavior

Slide should switch when using custom prev/next buttons.

### How to reproduce

Create a light box with custom prev/next buttons.

**Comment by igordanchenko** [comment]
> When rendering a custom button, clicking the button does nothing. I'm assuming it's because an onClick isn't being passed through, but the buttonNext/buttonPrev doesn't expose anything to pass through. 

You are correct, and this is the intended implementation. There are two separate render functions to render custom icons - `iconPrev` and `iconNext`, which I'm assuming folks would want to use in most cases as rendering custom icons preserves the original behavior. However, if you opt to render your custom navigation controls via `buttonPrev` / `buttonNext` render functions, you are in charge of implementing the whole user experience. If you really intend to go down this route, you can replicate the implementation of the [original](https://github.com/igordanchenko/yet-another-react-lightbox/blob/main/src/core/modules/Navigation.tsx) navigation buttons.

> I have also just tried setting the onClick to set the index to the next image, but the images don't slide automatically when changing it manually.

This is also the intended implementation in the current version of the library. The [documentation](https://yet-another-react-lightbox.com/documentation) is crystal clear about this.
