### ISSUE TITLE
Typescript error: Type expected in interface SlotCSSProperties

### ISSUE THREAD

**Issue by DariaKalinina** [igordanchenko/yet-another-react-lightbox#92]
### Describe the bug

Hello, see bug then I started project

```
[!] (plugin Typescript) TS1110: Type expected.
node_modules/yet-another-react-lightbox/dist/types.d.ts (60:11)

interface SlotCSSProperties extends React.CSSProperties {
    [key: `--yarl__${string}`]: string | number;
}
```

### Expected behavior

no bug)

### How to reproduce

step to reproduce - start build project with rollup

**Comment by igordanchenko** [comment]
What is your version of TypeScript?

**Comment by DariaKalinina** [comment]
> What is your version of TypeScript?

4.0.3

**Comment by igordanchenko** [comment]
Upgrading your TypeScript version should resolve this error. TS 4.1 is probably the lowest TypeScript version that can handle template literal types.
