### ISSUE TITLE
Implementation in NextJS throws error with image strings

### ISSUE THREAD

**Issue by Gr33nLight** [igordanchenko/yet-another-react-lightbox#93]
### Describe the bug

Hello, 
I'm trying to use the gallery and i'm passing the images in the slides prop as array of strings, so:
`[
  '/gallery/PSX_20200717_194817.jpg',
  '/gallery/PSX_20200717_194029.jpg',
  '/gallery/pic5.jpg',
  '/gallery/pic6.jpg',
  '/gallery/pic7.jpg'
]`

I'm using the NextJs implementation with the custom render as described here: 
https://yet-another-react-lightbox.com/examples/nextjs

When I run it though I get this error, note that i'm not passing a with, just the simple string with the image name. Adding a predetermined width/height fixes the issue, but images could be different sizes. Is there a way to fix this? Do I always have to know the image dimensions in advance? Thanks

```
next-dev.js?3515:25 Warning: `NaN` is an invalid value for the `width` css style property.
    at div
    at div
    at CarouselSlide (webpack-internal:///./node_modules/yet-another-react-lightbox/dist/core/modules/Carousel.js:26:26)
    at div
    at Carousel (webpack-internal:///./node_modules/yet-another-react-lightbox/dist/core/modules/Carousel.js:59:31)
    at div
    at Controller (webpack-internal:///./node_modules/yet-another-react-lightbox/dist/core/modules/Controller.js:25:23)
    at NoScroll (webpack-internal:///./node_modules/yet-another-react-lightbox/dist/core/modules/NoScroll.js:36:21)
    at div
    at Portal (webpack-internal:///./node_modules/yet-another-react-lightbox/dist/core/modules/Portal.js:37:19)
    at Root (webpack-internal:///./node_modules/yet-another-react-lightbox/dist/core/modules/Root.js:12:17)
    at EventsProvider (webpack-internal:///./node_modules/yet-another-react-lightbox/dist/core/contexts/Events.js:13:27)
    at TimeoutsProvider (webpack-internal:///./node_modules/yet-another-react-lightbox/dist/core/contexts/Timeouts.js:13:29)
    at LightboxStateProvider (webpack-internal:///./node_modules/yet-another-react-lightbox/dist/core/contexts/LightboxState.js:41:34)
    at LightboxPropsProvider (webpack-internal:///./node_modules/yet-another-react-lightbox/dist/core/contexts/LightboxProps.js:13:34)
    at Lightbox (webpack-internal:///./node_modules/yet-another-react-lightbox/dist/Lightbox.js:24:21)
    at div
    at FullScreenGallery (webpack-internal:///./components/FullScreenGallery.js:41:25)

```

### Expected behavior

The gallery should render without errors, as in the documentations its stated that the only required parameter for the slides prop is the image paths

### How to reproduce

I'm using the component like this, the images variable contains this: 

```
[
  '/gallery/PSX_20200717_194817.jpg',
  '/gallery/PSX_20200717_194029.jpg',
  '/gallery/pic5.jpg',
  '/gallery/pic6.jpg',
  '/gallery/pic7.jpg'
]
```

The SlideImage component is the exact same as described in your site.

```
    <div style={{ width: '100%', aspectRatio: '3 / 2' }}>
      <Lightbox
        // plugins={[Inline]}
        open={true}
        // close={() => setOpen(false)}
        // slides={[image1]}
        slides={images}
        render={{ slide: SlideImage }}
      />
      {/* <ReactImageGallery showPlayButton={false} items={images} /> */}
    </div>

```

**Comment by igordanchenko** [comment]
Please read the documentation. The `slides` prop accepts an array of objects, not strings. What you want to do is to pass your file names as `{src: "…"}`.

**Comment by igordanchenko** [comment]
Also, I’m pretty sure the Next.js image renderer would fail if you do not pass width and height. That example assumes that you import your images, and Next.js automatically provides width and height for each image.

**Comment by Gr33nLight** [comment]
I tried also by modifying the next/image with layout="fill", but again, the width and height appear to be required by the library

**Comment by Gr33nLight** [comment]
I assume then that width and height are required when using the NextJS image component, as I can see it is reading the props " slide.width" and " slide.height".

**Comment by igordanchenko** [comment]
Yes, the implementation posted on the documentation website requires image dimensions since it assumes that images are imported via `import` statement. Is there any particular reason you are not importing the images?

**Comment by Gr33nLight** [comment]
> Yes, the implementation posted on the documentation website requires image dimensions since it assumes that images are imported via `import` statement. Is there any particular reason you are not importing the images?

Since the images to add to the slideshow could vary overtime, I wanted to fined a solution that didn't involve changing the JS over time. So for example, get the images names with a glob read or a yml file containing the images to show for easy editing by non developers as well. Sorry if this is too specific

**Comment by Gr33nLight** [comment]
Managed to sorta fix it by using this component for the NextJSImage component: 
```
    <div key={slide} className="relative w-full h-full bg-black">
      <Image
        layout="fill"
        loading="eager"
        objectFit={cover ? 'cover' : 'contain'}
        placeholder="blur"
        blurDataURL={`data:image/svg+xml;base64,${toBase64(shimmer(384, 256))}`}
        draggable={false}
        alt="img"
        src={slide}
      />
    </div>

```

By doing it like this, i'm losing the "sizes" prop in the next Image which I'm still evaluating the advantages of

**Comment by igordanchenko** [comment]
> By doing it like this, i'm losing the "sizes" prop in the next Image which I'm still evaluating the advantages of

Yes, it's sort of a workaround, but without `sizes` your users' browsers will be downloading images of higher resolution than needed since all images will be assumed to be `100vw` wide. Also, smaller images will be scaled up to take all available space.

But since you are using Next.js, and it sounds like you are hosting all your images locally, I'd still recommend obtaining dimensions of your images at build time. Here are several options.

1) Use the [require.context](https://gist.github.com/igordanchenko/da9a809f3ede9f5484639967ef2e5b8a) trick (this way you also get the `blurDataURL` for free):

```js
const importAll = (context) => context.keys().map((key) => context(key).default);

const images = importAll(require.context('../public/images/', false, /\.(?:jpg|jpeg|png|gif|webp)$/));

export default function Page() {
  return (
    <Lightbox 
      slides={images.filter((image) => ... )}
      render={{slide: NextJsImage}}
      // ...
    />
  );
}
```

2) Use `getStaticProps` (you'll need to remove `placeholder="blur"` in this case):

```js
import fs from "fs";
import path from "path";
import imageSize from "image-size"
import Lightbox from "yet-another-react-lightbox"

export async function getStaticProps() {
    return {
        props: {
            images: fs.readdirSync(path.resolve("public/images")).map((file) => {
                const {width, height} = imageSize(path.resolve("public/images", file))
                return {src: `/images/${file}`, width, height}
            })
        }
    }
}

export default function Page({images}) {
  return (
    <Lightbox 
      slides={images.filter((image) => ... )}
      render={{slide: NextJsImage}}
      // ...
    />
  );
}
```

**Comment by Gr33nLight** [comment]
I implemented the second version and it works fine, thanks!
