### ISSUE TITLE
Issue with index view in v3.1.0

### ISSUE THREAD

**Issue by mtr1990** [igordanchenko/yet-another-react-lightbox#94]
### Describe the bug

Wrong display of current index in v3.1.0

### Expected behavior

Display current  index exactly as in v2.6.2

### How to reproduce

I have reproduced the behavior through the video here:

For: "yet-another-react-lightbox": "^2.6.2", (WORK)
https://www.dropbox.com/s/fhklh90zwuptpf8/light-box-01.mp4?dl=0 

For: "yet-another-react-lightbox": "^3.1.0", (NOT WORK)
https://www.dropbox.com/s/7wcrmul4ycrjo13/light-box-02.mp4?dl=0

<img width="623" alt="Screenshot 2023-03-25 at 14 24 43" src="https://user-images.githubusercontent.com/13531993/227703458-7b2c0792-66e1-4946-a5eb-5a553685e9f9.png">

```js
 <ReactLightbox
        slides={slides}
        animation={{ swipe: 240 }}
        carousel={{ finite: totalItems < 5 }}
        controller={{ closeOnBackdropClick: true }}
        plugins={getPlugins({
          disabledZoom,
          disabledVideo,
          disabledCaptions,
          disabledSlideshow,
          disabledThumbnails,
          disabledFullscreen,
        })}
        // "yet-another-react-lightbox": "^2.6.2",
        // on={{
        //   view: (index: number) => {
        //     console.log('index', index);
        //     if (onGetCurrentIndex) {
        //       onGetCurrentIndex(index);
        //     }
        //   },
        // }}
        // ----------------------------------------
        //  "yet-another-react-lightbox": "^3.1.0",
        on={{
          view: ({ index }: { index: number }) => {
            console.log('index', index);
            if (onGetCurrentIndex) {
              onGetCurrentIndex(index);
            }
          },
        }}
        toolbar={{
          buttons: [
            <DisplayTotal
              key={0}
              totalItems={totalItems}
              disabledTotal={disabledTotal}
              disabledCaptions={disabledCaptions}
            />,
            'close',
          ],
        }}
        render={{
          iconClose: () => <Iconify width={ICON_SIZE} icon="carbon:close" />,
          iconZoomIn: () => <Iconify width={ICON_SIZE} icon="carbon:zoom-in" />,
          iconZoomOut: () => <Iconify width={ICON_SIZE} icon="carbon:zoom-out" />,
          iconSlideshowPlay: () => <Iconify width={ICON_SIZE} icon="carbon:play" />,
          iconSlideshowPause: () => <Iconify width={ICON_SIZE} icon="carbon:pause" />,
          iconPrev: () => <Iconify width={ICON_SIZE + 8} icon="carbon:chevron-left" />,
          iconNext: () => <Iconify width={ICON_SIZE + 8} icon="carbon:chevron-right" />,
          iconExitFullscreen: () => <Iconify width={ICON_SIZE} icon="carbon:center-to-fit" />,
          iconEnterFullscreen: () => <Iconify width={ICON_SIZE} icon="carbon:fit-to-screen" />,
        }}
        {...other}
      />
```

### Additional context

Wondering if I missed something?

Thank you!

**Comment by igordanchenko** [comment]
Can you share the source code of the `DisplayTotal` button?

**Comment by igordanchenko** [comment]
Please also review the [v3 Breaking Changes](https://github.com/igordanchenko/yet-another-react-lightbox/issues/90) and the [documentation](https://yet-another-react-lightbox.com/documentation) of the `slides` prop. It looks like you may be re-rendering your component every time the lightbox index changes, and you are probably providing a non-stable `slides` array reference (though it's not clear from the code snippet that you provided above). But if that's the case, wrapping `slides` array in a `useState` / `useMemo` should resolve this issue.

**Comment by mtr1990** [comment]
Hi,

Sorry for not posting the full code. Because I combine with many other libraries.

I have solved this problem. Thanks for your feedback.

Liked this library so far. Keep up the good work.
