### ISSUE TITLE
Controls are disappearing when index and slides are changing

### ISSUE THREAD

**Issue by Kadchenko** [igordanchenko/yet-another-react-lightbox#98]
### Describe the bug

i have delete button on each slide and onDelete i remove one item from slides and change index respectively, then controls disappear from screen but still presented in dom

### Expected behavior

when change index and slides, i can see controls

### How to reproduce

change index and slides together

**Comment by igordanchenko** [comment]
Please share a demo or a code snippet reproducing this issue if you still require assistance with troubleshooting.
