### ISSUE TITLE
Lightbox needs to be opened, closed, then opened in order to load image

### ISSUE THREAD

**Issue by laurenschroeder** [igordanchenko/yet-another-react-lightbox#99]
### Describe the bug

When initially opening the lightbox, I see a loading symbol which displays indefinitely. It appears that the preload network requests are made, as I see them in the network tab. Once I close the lightbox and reopen it, I'm able to immediately see the images as expected. Are there any suggestions to fix or further troubleshoot what might be happening here?

### Expected behavior

I expect to see the image loaded when the lightbox first opens.

### How to reproduce

```
<Lightbox
        open={open}
        close={() => setOpen(false)}
        index={imageIndex}
        slides={lightboxData}
        carousel={{ finite: true, preload: 5, padding: "16px", spacing: "30%", imageFit: "contain" }}
        render={{
          slide: (slide) => CheckVideo(slide)
        }}
        plugins={[Zoom]}
  />


  const CheckVideo = (props: BgProps, cardRef?) => {
    if (props.video_id && props.video_source) {
      if (props.video_source.toLowerCase() == 'brightcove' && props.video_id != '') {
        return
        <div ref={cardRef}>
          <BrightcovePlayer video_id={props.video_id} />
        </div>;
      }
      if (props.video_source.toLowerCase() == 'youtube' && props.video_id != '') {
        return (
          <div ref={cardRef}>
            <YoutubePlayer video_id={props.video_id} />
          </div>);
      }
    }
    return null
  }
```

### Screenshots / Logs

![image](https://user-images.githubusercontent.com/20484946/228076877-e0477e86-e81f-4f4f-a50d-65579338872a.png)

**Comment by igordanchenko** [comment]
I'm unable to reproduce the issue based on the above code snippet. Please share a sandbox demonstrating the issue you are experiencing.
